### ISSUE TITLE
Waterlogging

### ISSUE THREAD

**Issue by WenXin20** [SammySemicolon/Malum-Mod#1]
It would be nice if waterlogging could be added for Item Stands, Item Pedestal, Spirit Jars, and perhaps even the Spirit Altar for potential decoration opportunities. Also, Ether and Ether Torches can be placed underwater but doesn't waterlog or pop out.

**Comment by SammySemicolon** [comment]
![image](https://user-images.githubusercontent.com/69329424/119316256-0cfd7780-bc77-11eb-87ea-1e02feb1c8f8.png)
Should work nicely now!

**Comment by SammySemicolon** [comment]
Stands and Pedestals will come soon too

**Comment by SammySemicolon** [comment]
![image](https://user-images.githubusercontent.com/69329424/119319155-61562680-bc7a-11eb-9926-0a2917c30829.png)

**Comment by WenXin20** [comment]
Thanks!
