### ISSUE TITLE
incompatibility with farming for blockheads

### ISSUE THREAD

**Issue by caligator** [SammySemicolon/Malum-Mod#10]
when you boot a world, FFB throws an error stating that it has a registry error 

"Expected item to be an item. was unknown string 'malum_runewood_sapling'"
can not find anything to fix this on FFB's end. isnt the sapling just a normal sapling?

**Comment by SammySemicolon** [comment]
The issue was quite literally me being incompetent and tired and using a "_" instead of a ":". Fixed in InDev

**Comment by muqsit-0010** [comment]
Any estimate on when this will be published? Unfortunately, makes a modpacks look very unpolished because you are bombarded with a bright red error message in game chat on every world load....

**Comment by drakray** [comment]
> 
> 
> Any estimate on when this will be published? Unfortunately, makes a modpacks look very unpolished because you are bombarded with a bright red error message in game chat on every world load....

you can fix it manually by editing the json file in the jar(its what I did), or maybe with a datapack, not sure about that one though
