### ISSUE TITLE
Curio infinite damage bug & use without wearing

### ISSUE THREAD

**Issue by VallenFrostweaver** [SammySemicolon/Malum-Mod#102]
Minecraft 1.18.2
Forge 40.1.54
Malum 1.3.7

Equip the Necklace of the Narrow Edge with any scythe. Unequip and re-equip the necklace. Repeat but at no time do you need to keep the necklace equipped. Each time it IS equipped it will increase the damage dealt by scythes by +2 for normal scythes or +2/+2 for Soul Stained Steel Scythes stacking each time (so then +4 then +6 and so on). This effect lasts until the player dies. 
EDIT: Equipping other curios gives benefits that will stay on the player even after the item is removed. i.e. Magebane belt give +3 Soul Ward that stays with the player even after it's removed (it then regenerates). Stays until death.

**Comment by SammySemicolon** [comment]
Yeah, this is 'intended' in the sense that. It's fun, so I'm not making a deliberate fix for it. It'll come in 1.4, which is basically just around the corner.

**Comment by VallenFrostweaver** [comment]
Ok. Glad that you are aware either way. :)
