### ISSUE TITLE
1.18.2 How to add mobs to the spirit loot table?

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [SammySemicolon/Malum-Mod#103]
When I was swimming around in atm7, I noticed aquaculture fish don't drop spirits, but ars nouveau mobs do. Haven't checked mana and artifice yet.
How do I add mobs to the loot table?

**Comment by SammySemicolon** [comment]
You can PR in some spirit files, but in general you just use a datapack with json files under data/malum/spirit_data/entity/

**Comment by SammySemicolon** [comment]
You can see how this fella did it here https://github.com/SammySemicolon/Malum-Mod/commit/574289b901ae9023a33bde4962bcc2fbe898a555
