### ISSUE TITLE
[feature request] Config option to reverse scroll wheel direction in Encyclopedia Arcana

### ISSUE THREAD

**Issue by Goldenlion5648** [SammySemicolon/Malum-Mod#106]
Currently the scroll wheel functionality behaves the opposite from the patchouli books (there it is scroll down to go forward a page, Malum is scroll up to go forward one page). Would it be possible for a config option to be added? (Or the behavior to be changed to match? I think its more intuitive to scroll down to advance, like opening a website, not scrolling up) I believe the `>` would just need to be changed to `<` here (unless a config option was added) https://github.com/SammySemicolon/Malum-Mod/blob/904e0d85a3d1474a9a1247d2c10cb0355d6064fd/src/main/java/com/sammy/malum/client/screen/codex/EntryScreen.java#L105

**Comment by SammySemicolon** [comment]
This functionality is added in 1.4.2
