### ISSUE TITLE
1.18.2 - Soul Stained Steel Scythe causes a crash when backstabbing with the parrying mod.

### ISSUE THREAD

**Issue by LordSeabass** [SammySemicolon/Malum-Mod#107]
Parrying has a feature that multiplies your damage when hitting an enemy from behind. But when doing this with the soul stained steel scythe it will cause a crash. I also made a issue on the Parrying mod's page, they said it was likely an issue with Malum. Here is the Issue I made on their page [Here](https://github.com/theishiopian/Parrying/issues/38)

Crash Report: [Here](https://pastebin.com/JTS8CYuc)
Log: [Here](https://pastebin.com/Jpx5km69)

Forge: 40.1.54
Minecraft version: 1.18.2
Parrying version: 2.5.3
Malum version: 1.3.7
Lodestone Lib version: 1.0

**Comment by SammySemicolon** [comment]
Could you see if this bug exists in https://maven.blamejared.com/com/sammy/malum/malum/1.18.2-1.4-53/ ? 
If not, then I'll consider it fixed :) (I have zero idea what this is)
You'll also need Lodestone 1.1
https://maven.blamejared.com/team/lodestar/lodestone/lodestone/1.18.2-1.1.7/

**Comment by LordSeabass** [comment]
It actually doesn't happen in these versions. It is fixed.

**Comment by SammySemicolon** [comment]
I consider it closed then

**Comment by theishiopian** [comment]
Will close it on my end as well.
