### ISSUE TITLE
[BUG][1.18.2] Runewood/Soulwood leaves' distance block property is always 1 when grown

### ISSUE THREAD

**Issue by thetos7** [SammySemicolon/Malum-Mod#108]
Malum version: 1.3.7

# What happened
When malum trees grow naturally or with bonemeal, the distance property of leaves is always set to 1, however, it should be set to the distance (26-neighbourhood distance[^1]) to the nearest log, like vanilla trees do. This happens correctly when growing the trees with the Create mod's tree fertilizer.

# Examples
## Incorrect distances (grown with bonemeal)
![2022-08-12_14 55 41](https://user-images.githubusercontent.com/33055824/184358764-510a64ee-384e-4ab7-8693-093dd8a6ca61.png)

![2022-08-12_14 55 43](https://user-images.githubusercontent.com/33055824/184358786-8bbbafe4-6edb-4572-bc40-ab660e5ffa52.png)
The distance value should be 2.

## Correct distances (grown with the Create mod's tree fertilizer)
![2022-08-12_14 55 49](https://user-images.githubusercontent.com/33055824/184359050-42b7ecad-b276-4ad3-8d8d-930d4574542a.png)

![2022-08-12_14 55 51](https://user-images.githubusercontent.com/33055824/184359598-63521245-9b50-4fea-bdeb-e04c1959e068.png)

## Oak tree for comparison
![2022-08-12_15 08 19](https://user-images.githubusercontent.com/33055824/184360396-38862c3d-7731-4a5b-bfbf-89f98ec5b0e4.png)
![2022-08-12_15 08 23](https://user-images.githubusercontent.com/33055824/184360408-de4f5f94-f351-439c-b9c9-47f45d10f81f.png)

# Steps to reproduce
- place runewood sapling or soulwood sapling
- grow the sapling (wait or bonemeal)
- inspect leaves' block properties with F3 (right side)

[^1]: schema of 26-neighbourhood on page 3: https://arxiv.org/pdf/1803.04190.pdf

**Comment by thetos7** [comment]
The distance values (for runewood trees) seem to be initially set to 1 here:

https://github.com/SammySemicolon/Malum-Mod/blob/904e0d85a3d1474a9a1247d2c10cb0355d6064fd/src/main/java/com/sammy/malum/common/worldgen/RunewoodTreeFeature.java#L223

**Comment by SammySemicolon** [comment]
Yeah hmm, I kind of put this problem aside when developing the feature at first.  I don't think it's too big of a deal.
If I don't set it to 1, I believe some of the leaves would start to decay instantly, which made the trees look bad. I'm not sure what the best solution here is.

**Comment by thetos7** [comment]
It's minor I guess, during normal gameplay with malum only, it doesn't affect much, leaves decay normally and stuff. However I think this breaks the behavior of Create's saws, for example, which do not break all the leaves currently (they should).

So it may only create minor incompatibilities.

**Comment by TristanKing0** [comment]
Not only does this break automatic Create tree farms, it also breaks tree chopping mods such as HT's TreeChop from working correctly.

**Comment by SammySemicolon** [comment]
![image](https://user-images.githubusercontent.com/69329424/190910773-3694cd50-26d6-44f2-90c1-7d2c8fd77905.png)
I don't even understand why this happens but like, if I don't force the leaves into a distance of 1 they just get thanos snapped after the game ticks a bit.

**Comment by SammySemicolon** [comment]
I made all the leaves tick the moment they're placed as a test, it definitely works but it might not be the best solution.
