### ISSUE TITLE
Crash with Rubidium installed :(

### ISSUE THREAD

**Issue by 4AC11** [SammySemicolon/Malum-Mod#109]
If rubidium is installed, killing an enemy with a spirit stealing weapon will cause the game to crash and the world to become unplayable. :(

[latest.log](https://github.com/SammySemicolon/Malum-Mod/files/9339407/latest.log)

**Comment by SammySemicolon** [comment]
Go to your config folder, look for the client config for ortus lib, and turn off particle buffering.

**Comment by 4AC11** [comment]
It worked!! I can't believe it was that simple! 

For future googlers who also experience the "Unexpected exception thrown!" issue, hopefully typing that out will lead you here to this solution.

**Comment by SammySemicolon** [comment]
There should be a fix coming soon in 1.4, the issue doesn't happen on the quilt version so we worked out a solution for the forge one too.

**Comment by copygirl** [comment]
Would you suggest changing that setting in general, or only until the fix is available in Malum?

**Comment by SammySemicolon** [comment]
You can just change the setting, it makes the particles render before clouds, which looks bad, but besides that it's harmless.

**Comment by copygirl** [comment]
May I request leaving this issue open? Issue is not fixed - it requires user intervention.
Other issues have already been opened running into the same problem.
