### ISSUE TITLE
Feature Request: Some kind of Spirit Funnel/Magnet/Hopper

### ISSUE THREAD

**Issue by puncrafter** [SammySemicolon/Malum-Mod#110]
The corrupted wicked rite effect leads me to believe that spirit collection is supposed to be automatable, but conventional means of picking up items don't work on spirits. I think there should be some kind of block (or entity, I suppose) that is either capable of picking up spirits, or perhaps moving them to a more convenient location, if you still want the player to be necessary for spirit collection.

**Comment by SammySemicolon** [comment]
Yeah, we'll have some sort of spirit hopper eventually.

**Comment by SammySemicolon** [comment]
In 1.4 I added a config option that makes spirits instead simply drop as normal item entities, this should do a solid for the time being
