### ISSUE TITLE
Killing an enemy with scythe crashes the game

### ISSUE THREAD

**Issue by Vorazcx** [SammySemicolon/Malum-Mod#111]
Every time i try to kill an enemy with the scythe it says "saving world" then boots me off the game, I'm not sure how to fix this or what's causing this but it's very annoying.

**Comment by corintalisman** [comment]
I can confirm this also happens on my custom modpack server. For us this specifically happens with the Soul Stained Scythe when hitting a large number of mobs. Using the Crude Scythe didn't cause it to crash.

**Comment by SammySemicolon** [comment]
It's something to do with magic damage & sweep recursion. For now all you can do is not use the SSS scythe, everything else will work.
