### ISSUE TITLE
Game crash when harvesting sap with a bottle

### ISSUE THREAD

**Issue by Kawapatch** [SammySemicolon/Malum-Mod#114]
Hello!

My game crashed earlier when I went to collect sap from one of your trees. In this instance I harvested the logs with an axe then placed them down later to collect the sap. When reloading the world, the bottle gets filled with sap but the sap stays in the log. I think there must be some sort of weird interaction with another mod I have, although i've got no clue what that could be. I'll just avoid the sap for now, but I thought it would be a good idea to mention it here anyway.

Here's the error message:
![image](https://user-images.githubusercontent.com/36980992/185771575-e823b7cd-2801-455f-a8b3-8d1eefe553a9.png)

I've also attached my crash report file.

Thank you for the amazing mod Sammy, hope you have a good one!

[crash-2022-08-21_10.44.41-client.txt](https://github.com/SammySemicolon/Malum-Mod/files/9388267/crash-2022-08-21_10.44.41-client.txt)

**Comment by SammySemicolon** [comment]
This is a conflict with rubidium, go to ortus-lib client config and turn off particle buffering.

**Comment by Kawapatch** [comment]
> This is a conflict with rubidium, go to ortus-lib client config and turn off particle buffering.

Ahhh it would be that wouldn't it haha. Thank you so much, sorry for taking your time!
