### ISSUE TITLE
[BUG] Game crushed when i tride to perfom a ritual 

### ISSUE THREAD

**Issue by Bo-Brat** [SammySemicolon/Malum-Mod#115]
The game crashed whilst ticking block entity Error: java.lang.NoClassDefFoundError: com/sammy/malum/core/init/particles/MalumParticles
[crash-2022-08-23_21.44.50-client.txt](https://github.com/SammySemicolon/Malum-Mod/files/9409950/crash-2022-08-23_21.44.50-client.txt)

**Comment by SammySemicolon** [comment]
Go to the malum client config file and turn off particle buffering, assuming that's a thing on 1.16.5
