### ISSUE TITLE
Mod isn't licensed

### ISSUE THREAD

**Issue by TheParadoxBox** [SammySemicolon/Malum-Mod#118]
Simple as that. This makes for legal complications if somebody wants to reuse the source; yes, the source is available, but no, you do not have the right to reuse it. My suggestion is to license the source code as open-source and the assets as all rights reserved (proprietary) or Creative Commons (reusable).

**Comment by SammySemicolon** [comment]
What is the goal of this github issue, the mod is licensed as All Rights Reserved, don't think anything different is needed.

**Comment by briarss** [comment]
what is a pirate's favourite license

**Comment by TheParadoxBox** [comment]
> What is the goal of this github issue, the mod is licensed as All Rights Reserved, don't think anything different is needed.

I figured it might've been an oversight, seeing as the source is available but not reusable. If that's what you're aiming for, though, go ahead.

**Comment by SammySemicolon** [comment]
If someone wants to use some of my code they need to ask, that's pretty much it from what I read. I try to make everything that could be useful to others end up in the library mod for malum; which anyone can implement in their own project.
