### ISSUE TITLE
Suggestion: Belt Curio Recipe

### ISSUE THREAD

**Issue by Merithor** [SammySemicolon/Malum-Mod#12]
Conflicted Soulstone: 
Rune Table. Radiant Soulstone, 10x Wicked Spirit and 10x Sacred Spirit. Looks like a spikier version of Radiant Soul stone with red lightning shocks.

Girdle of Spiritual Eruption
Made with Gilded Belt, Hallowed and Soul Stain Spirit Resonator, Nether Star, Conflicted Soulstone, and 10x Infernal Spirits.

Spirits are turned in Explosive shards. These shards gathered turn into throwable bomb, Does no block damage, Damage is 3 hearts of piercing damage (ignore armor).
"This Belt was created by a madman. A Madman who was mad at armored foes, reaping their souls took a toll on his Scythe. In a fit of rage he tossed his belt against the wall near his Altar. His sacred souls and wicked souls began fighting for a soulstone that fell, turning the stone something odd and ominous.
In awe of the soulstone, he attempted to combine it with the belt with some Infernal spirits, a Nether Star as a catalyst, and both metallic resonators.
Wearing it, he slain a skeleton, which instead dropped a bright red soul, he picked it up and tossed it at a Diamond laden Zombie. It exploded and destroyed the zombie from within."

**Comment by SammySemicolon** [comment]
I've wanted to add explosive spirits for quite a while, I'll be sure to add this <3

**Comment by SammySemicolon** [comment]
Closing this, I'm still intending to add it to the mod just not sure when :)
