### ISSUE TITLE
[1.18.2] Crash Caused by Missing Ortus When Lodestone installed

### ISSUE THREAD

**Issue by MokahTGS** [SammySemicolon/Malum-Mod#121]
Using version malum-1.18.2-1.3.7.jar and lodestone-1.18.2-1.1.jar with Forge 40.1.76 is causing a crash saying that the pack is missing ortus...

Crash log: https://pastebin.com/B06qz5Dr

Not sure what to do here.  I installed the mod via the Curse Launcher and it doesn't seem to be grabbing the right files.

**Comment by SammySemicolon** [comment]
Downgrade lodestone to ortus lib, or upgrade malum to the 1.4 beta version.
