### ISSUE TITLE
1.4 ver crash

### ISSUE THREAD

**Issue by mewnn** [SammySemicolon/Malum-Mod#123]
[crash-2022-09-07_12.50.53-client.txt](https://github.com/SammySemicolon/Malum-Mod/files/9505581/crash-2022-09-07_12.50.53-client.txt)

client's failing to load
on 1.3.7 version everything was good, maybe this crash report would be useful.

**Comment by SammySemicolon** [comment]
you're still running 1.3.7 though

**Comment by mewnn** [comment]
> you're still running 1.3.7 though

LMAO no way, cause the file was clearly 1.4 and after crash I changed it to 1.3.7 and it loaded normally
well, I’ll try again tomorrow :<

**Comment by mewnn** [comment]
> you're still running 1.3.7 though

I've found out, I won't give crash report after crashing. But I can give you logs. Is it even necessary?
[crash.txt](https://github.com/SammySemicolon/Malum-Mod/files/9525094/crash.txt)

**Comment by mewnn** [comment]
I'm just dumb and haven't updated lodestone ):

**Comment by SammySemicolon** [comment]
All good :)
