### ISSUE TITLE
Tetra Integration does not spawn spirits

### ISSUE THREAD

**Issue by annastropha** [SammySemicolon/Malum-Mod#124]
forge 40.1.76
curios 1.18.2-5.0.7.1.jar
malum 1.18.2-1.3.7.jar
mutil 1.18.2-4.5.0.jar
ortus 1.18.2-1.0.jar
tetra 1.18.2-4.9.3.jar

Steps to reproduce:

1. Spawn a Netherite Hammer, Soul Steel Sword, Soul Steel Ingot, and workbench from the creative menu.
2. Place the Workbench
3. Replace the hilt of the Soul Steel Sword using a Soul Steel Ingot
4. /summon minecraft:creeper
5. Kill the Creeper, observe lack of spirits

**Comment by SammySemicolon** [comment]
Hm, what if you replace the blade of an iron sword using soul stained steel. Maybe using a SSS tool as a base causes this weirdness. I'll look into it.

**Comment by annastropha** [comment]
Unfortunately, this has the same outcome.  Of possible note is that Soul Stained Steel does not visually apply any stats to the tool in the way other materials do, such as Botania's Mana Repair.

[Soul Stained Steel Blade](https://i.imgur.com/o4uGFCP.png)

[Manasteel Blade](https://i.imgur.com/meOkGa4.png)

**Comment by SammySemicolon** [comment]
Oh wait! I know what's up. I had to comment out the tetra compat because at the time of the malum release tetra wasn't on 1.18.2.
You'll have to move to malum 1.4, or just deal with it for now.
