### ISSUE TITLE
[1.18.2] mod asks for orthus, but that library does not seem to exist 

### ISSUE THREAD

**Issue by AbsolemJackdaw** [SammySemicolon/Malum-Mod#125]
trying to use maven integration to use malum as a base for an addon
but i get this instead

versions used are 
malum 1.4
lodestone (only one file available)
curios 5.0.7.1

I couldnt find orthus anywhere on CF and dont really know what to do now
![image](https://user-images.githubusercontent.com/3628535/189008266-ad7e599e-d128-44fe-9854-f8fa043131c1.png)

**Comment by EpicSquid** [comment]
Are you sure your not using malum 1.3? Ortus was renamed to lodestone and malum 1.4 uses lodestone.

**Comment by mewnn** [comment]
ortus and lodestone are one thing though

**Comment by AbsolemJackdaw** [comment]
Turns out forge gradle had a massive problem removing my old download cache from updating from a previous version. 
It was no one's fault but gradle's. 
thanks for fast response either way !
