### ISSUE TITLE
New Update - Issue with Soulwood Signs

### ISSUE THREAD

**Issue by ZirWolf** [SammySemicolon/Malum-Mod#127]
When I placed a Soulwood sign down for decoration it closed the client (no crash report) and once I was able to log back into the server, the sign was invisible.

Version 1.18.2-1.4

**Comment by SammySemicolon** [comment]
hm, that's. Really odd. It not rendering is technically intentional since it normally crashes anytime it renders for whatever reason. 
Can you send me latest.log ?

**Comment by ZirWolf** [comment]
[latest.log](https://github.com/SammySemicolon/Malum-Mod/files/9541284/latest.log)

I hope this is the correct one? I'm very new to this, sorry!

**Comment by SammySemicolon** [comment]
You're fine :) Thank u for bringing up the issue

**Comment by SammySemicolon** [comment]
Sadly I can't help much seeing as you're having problems with the 1.16.5 version of the mod.
