### ISSUE TITLE
Malum Requires JEI

### ISSUE THREAD

**Issue by Jusey1** [SammySemicolon/Malum-Mod#128]
Essentially, Malum crashes the game if JEI isn't present because "Caused by 0: java.lang.NoClassDefFoundError: mezz/jei/api/ingredients/IIngredientType"... This can be pretty bad since some players might not be using JEI or using REI instead.

**Comment by SammySemicolon** [comment]
Is this a 1.18.2 issue?

**Comment by Jusey1** [comment]
Yes, and argh. Sorry. I forgot to put [1.18.2] in the name.

**Comment by SammySemicolon** [comment]
Can you send me the full log?

**Comment by FearAK** [comment]
I have this issue aswell when I tried to switch from jei to rei. Did you ever find a fix?

**Comment by FearAK** [comment]
[latest.log](https://github.com/SammySemicolon/Malum-Mod/files/9960956/latest.log)
