### ISSUE TITLE
Malum Crashes Game On Startup.

### ISSUE THREAD

**Issue by toErIpNid** [SammySemicolon/Malum-Mod#129]
Title.

Mod Ver: 1.3.7
Forge Ver: 40.1.80

Crash Log: https://pastebin.com/feXFT4en

**Comment by SammySemicolon** [comment]
This isn't the full log, could you send me a crash log instead?

**Comment by toErIpNid** [comment]
This is the latest log in the folder: https://hastebin.com/libajuhuxi.sql

Here's what the launcher says in case it helps.:
![wut](https://user-images.githubusercontent.com/78389307/190482812-d722d1b5-81b5-4a0c-9edb-d220feabda96.PNG)

**Comment by toErIpNid** [comment]
Update, mod still crashes but here's the log with Not Enough Crashes installed. 

https://hastebin.com/izisufaluy.sql

**Comment by SammySemicolon** [comment]
Update malum to 1.4, or downgrade lodestone to ortus-lib.
