### ISSUE TITLE
mod malum requires mod ortus but this mod does not exist

### ISSUE THREAD

**Issue by ComeBelin** [SammySemicolon/Malum-Mod#130]
![image](https://user-images.githubusercontent.com/48830039/190431518-65246245-b4a6-4077-8c4a-fd4feb4d0076.png)

**Comment by QinomeD** [comment]
It's now Lodestone, older versions of malum need older version of Lodestone, which was then named Ortus. Update Malum or use Ortus (Lodestone now, as I said)

**Comment by ComeBelin** [comment]
okay thanks
