### ISSUE TITLE
Book missing text

### ISSUE THREAD

**Issue by mewnn** [SammySemicolon/Malum-Mod#132]
![Screenshot_54](https://user-images.githubusercontent.com/93125234/190969277-1eba0976-3537-491a-913b-62fd948b4201.png)
![Screenshot_55](https://user-images.githubusercontent.com/93125234/190969280-5624e7ce-2f2a-483f-9c65-ace249fbd183.png)

Idk if it's intended, but issuing to make sure 0^0

**Comment by SammySemicolon** [comment]
Yeah 1.4 is in a beta state, I just cannot find the motivation to actually write these entries.

**Comment by mewnn** [comment]
> Yeah 1.4 is in a beta state, I just cannot find the motivation to actually write these entries.

If you need something like book entries or item textures, I can do that for you. 
Of course, only if you'd be okay with it.

**Comment by SammySemicolon** [comment]
Textures aren't that big a deal, text is just annoying to write and hard to find motivation for. If you feel like it, go for it.

**Comment by Gartebex-Ugandi** [comment]
Hey, dont worry about the text that much, i think it would be really nice to have it shorter. Its kinda annoying to read :D (at least for me).

**Comment by Gartebex-Ugandi** [comment]
May i rewrite perhaps ?

**Comment by SammySemicolon** [comment]
there's no need to rewrite anything.

**Comment by Gartebex-Ugandi** [comment]
ok

**Comment by Gartebex-Ugandi** [comment]
Do you at least mind to make it a bit shorter ?

**Comment by Shibva** [comment]
@SammySemicolon hey um, to extend this issue or something I think some content from the book is missing; a good number of the trinkets lack entries since the rearrangement and some things afaik are missing such as the use of weaves and stuff

**Comment by SammySemicolon** [comment]
I think 2 trikets lack entries, and the prideweave stuff. They're not too significant right now, so I think it's fine.

**Comment by Shibva** [comment]
also nirate I belive

**Comment by Gartebex-Ugandi** [comment]
> there's no need to rewrite anything.

A bit of an misunderstanding, I didnt wanted to hate or anything, what i might wanted to say is that i personnaly woudnt even mind if the text would be a bit shorter, i find it too much text, and that i might could help with the text if you cant find motivation for it (but i havent noticed someone already wanted to).

**Comment by SammySemicolon** [comment]
I would like to add some config option that changes all the text to like, technical speak.
Just for the sake of having it.
But that's a thing for the future.
