### ISSUE TITLE
Malum RecipeTypes Not Registered Properly

### ISSUE THREAD

**Issue by vertexcubed** [SammySemicolon/Malum-Mod#133]
As far as I can tell, all recipe types in malum aren't registered properly, meaning you cannot use tweaker mods such as CraftTweaker or KubeJS to add or remove any recipes. This makes working with Malum much more difficult from a pack development standpoint.

Tested as of Malum v1.4.2 and Lodestone v1.2

**Comment by SammySemicolon** [comment]
Yeah, this is like- the next bug to tackle that's on my to-do list. Hopefully a fix will be out sometime this week
