### ISSUE TITLE
CTD when installed in mod pack

### ISSUE THREAD

**Issue by AngleWyrm10** [SammySemicolon/Malum-Mod#135]
[This mod pack](https://www.curseforge.com/minecraft/modpacks/anglewyrms-collection/files/4000244) crashed after installation of Malum-1.18.2-1.3.7.jar through CurseForge launcher

[Crash Report](https://gist.github.com/AngleWyrm10/0484418d3de26f8278bd91b1fd31f554)

**Comment by SammySemicolon** [comment]
Could I have the full latest.log ?

**Comment by EpicSquid** [comment]
Closing since it is stale
