### ISSUE TITLE
Ortus is no Lodestone

### ISSUE THREAD

**Issue by alexlarraga1** [SammySemicolon/Malum-Mod#136]
This may cause crash in a future or with updated versions

**Comment by Nysterian** [comment]
I'm unsure if this is the same problem that I'm having, but I just installed malum into a new instance of MC using CurseForge's Overwolf app, and it did install Lodestone, but when I open MC, I get the following error:
![GUl2oBC 1](https://user-images.githubusercontent.com/30325333/202614189-88c8cd93-c447-437a-8c80-8899a5240321.png)

**Comment by starryfae** [comment]
+1, I literally just installed both (newest) and it is asking for Ortus.

**Comment by moninformateur** [comment]
I honestly don't get this. Why is the mod not updated to the new library....

**Comment by EpicSquid** [comment]
Make sure to use the beta version of malum on curseforge (1.4 or later), that will solve the issue
