### ISSUE TITLE
Necklace of tidal affinity texture incomplete

### ISSUE THREAD

**Issue by Warhand** [SammySemicolon/Malum-Mod#139]
The texture for the necklace of tidal affinity is doesn't seem to fully exist, and is only a tan line.
I've checked and this isn't an issue with any of my other installed mods, or a glitch, the texture file itself is just that image.

![image](https://user-images.githubusercontent.com/29134223/193490884-1b2c6708-f2fd-44b1-8908-ada1cde15e1a.png)

**Comment by SammySemicolon** [comment]
This is quote on quote intended as I am lazy and the 1.4 release is a beta, will be fixed in full release.
