### ISSUE TITLE
Ether flame texture disappears after leaving and re-entering a server

### ISSUE THREAD

**Issue by LarkiJay** [SammySemicolon/Malum-Mod#140]
I have a 1.18.2 modded forge server that I play with one other person. We have several mods including Malum. 

The issue occurs whenever I close and reopen Minecraft, and re-enter the server. The previously working ether flame texture on my Twister Ether Braziers no longer shows, only the brazier itself. This doesn't affect the light given off of the block, only the texture.

The texture reappears if I break the brazier and place it down again, but it just disappears again after I leave and re-enter the server (every time without fail). I imagine this may also be the case for any and all other types of ether/iridescent ether braziers.

Below I attached two pictures of the brazier with the flame texture gone, and the last picture is when it looks normal.

![image](https://user-images.githubusercontent.com/115133395/194219388-3f250eb9-3b97-4970-af56-7d20d8b6f5a4.png)
![image](https://user-images.githubusercontent.com/115133395/194219434-f57b9817-2cd3-47ed-922a-1501e40010c0.png)
![image](https://user-images.githubusercontent.com/115133395/194220779-db21b0ce-2e6f-4202-b888-6aef07006b03.png)

**Comment by SammySemicolon** [comment]
This is fixed in 1.4, await a stable build of it and then move over :) Or move over now, it's not really unsafe.
