### ISSUE TITLE
[1.16.5] Error in console on server load - Error msg is: Unknown registry element com.sammy.malum.common.worldgen.RunewoodTreeFeature@21c8804f         

### ISSUE THREAD

**Issue by ProsperCraft** [SammySemicolon/Malum-Mod#141]
https://gist.githubusercontent.com/ProsperCraft/71c239d270d0f7ec14aa1f0a8e488ecd/raw/15a3f3dd92f8aa086cf1cdf574bc981a740fcef3/gistfile1.txt

malum-1.16.5-0.3.0

**Comment by SammySemicolon** [comment]
I can't really do much about 1.16.5, sorry

**Comment by Deepfriedyag** [comment]
I got the same issue. Does that mean 1.16.5 is no longer supported?
