### ISSUE TITLE
[Suggestion] Allow Tyrving to use Haunted

### ISSUE THREAD

**Issue by 4AC11** [SammySemicolon/Malum-Mod#143]
In its current state, Tyrving feels a little... underwhelming. It seems like it's meant to be a powerful sword, even an upgrade to the Soul Stained Steel sword, but it almost feels like a downgrade with how it sacrifices and _entire point_ of physical damage in exchange for converting the remaining damage to Magic type. This may be strong against players with armor, but most mobs will be basically unaffected and even then it doesn't seem like it's really worth using the Tyrving over even a diamond sword.

This only gets worse once enchantments come into the picture, because despite Tyrving being a weapon entirely based around dealing magic damage, you find that it.... can't get the enchantment for dealing extra magic damage. 

Allowing Tyrving to accept and use both Sharpness AND Haunted, while converting Sharpness' physical damage to Magic, would actually make the weapon worth using in its niche, and make it generally a more unique item outside of its sound and particle effects.

**Comment by SammySemicolon** [comment]
Haunted might not be staying in the mod forever, it feels a little boring and I wanna include something cooler.
Though, I don't really understand this suggestion, the tyrving deals a heart of damage per spirit found within an entity, most enemies have at least 2 spirits within them, which would equal to 4 damage, 9 total. I'll consider buffing it a little, but we'll see.
