### ISSUE TITLE
[Compat] REI item search not working when Malum is installed

### ISSUE THREAD

**Issue by Raidobw2** [SammySemicolon/Malum-Mod#145]
Hello!

I was planning a modpack update ahead a little bit and noticed that Roughly Enough Items no longer functioned properly if any of the Malum updates from 1.4 is installed ( in Minecraft 1.18.2 ).

I'm not sure on the error itself, but I am inclined to think maybe the Water Necklace (Necklace of Tidal Affinity) is part of the issue.

When searching `cobblestone` in REI with Malum installed, nothing "moves":
![image](https://user-images.githubusercontent.com/17010632/196827532-df0ddf01-a049-4c59-98bd-a031aeb81fad.png)

When searching `@malum` in REI with Malum installed, it works:
![image](https://user-images.githubusercontent.com/17010632/196827568-72c36bd2-217c-4206-9180-e0b35dee1fec.png)

When searching `cobblestone` again and Malum is not installed, it works:
![image](https://user-images.githubusercontent.com/17010632/196828148-a4840401-0706-46f4-82d8-222abc96ae41.png)

Versions:
`malum-1.18.2-1.4.3.1.jar`
`lodestone-1.18.2-1.2.jar`
`RoughlyEnoughItems-8.3.549.jar` & Dependencies installed from the CurseForge App automatically
Forge 40.1.84

This is the relevant information:
https://paste.feed-the-beast.com/view/6362ee22

As mentioned earlier this might have to do with the new necklaces

The water necklace is this one (is this the intended texture also?):
![image](https://user-images.githubusercontent.com/17010632/196828422-f1ce1a80-5d8b-45d2-ab77-0ec6ed2b0bcd.png)

I notice other necklaces share an "empty line" in REI (the description maybe?):
![image](https://user-images.githubusercontent.com/17010632/196828466-fda05a8e-074c-49a1-a7e8-96994eb53b3b.png)

For instance this necklace does not have an empty line:
![image](https://user-images.githubusercontent.com/17010632/196828492-2911da9e-a769-4a42-9139-ebfab0991def.png)

I believe this might also be an issue with REI, so I will report it to them and link the other issue here as well for convenience. Thanks for checking into it at some point!

**Comment by Raidobw2** [comment]
I've reported this to REI as well with as much info, please see linked issue and thank you ^

**Comment by Raidobw2** [comment]
I've spoken with the author of REI a bit the other day and they don't think it's caused by REI. They don't know why `net.minecraft.world.entity.ai.attributes.AttributeModifier` is missing, but they said maybe this is the wrong classloader:
![image](https://user-images.githubusercontent.com/17010632/197961872-dc4b9d6f-589a-4e70-a567-eef2fc2a8ea6.png)
I hope that helps

**Comment by gr8pefish** [comment]
FYI, just used the combo today with both mods updated (as it's been a while), and the above was a non-issue

**Comment by Raidobw2** [comment]
Alrighty, I'll take your word on it. I haven't been able to test this myself, but as you mentioned there's been quite a few updates since my report.
I'll close this then and assumed it was fixed, if I notice this again in the future I'll open a new issue.
Thanks gr8pefish for the comment 🙂
