### ISSUE TITLE
[1.18][Suggestion] Lower the amount of Saplings dropped from Runewood Trees

### ISSUE THREAD

**Issue by Filostorm** [SammySemicolon/Malum-Mod#146]
This kind of feels like a nitpick (sorry), but it seems like Runewood Trees drop a disproportionately high amount of saplings. One tree dropped 19. A full grown jungle tree dropped 8.

This basically leads to major inventory clutter if you're using them for building/charcoal etc.

Also wanted to note the mod looks awesome!

**Comment by SammySemicolon** [comment]
Are you using 1.3.7 ?  It's been changed in 1.4

**Comment by Filostorm** [comment]
Yep, 1.3.7. Thanks!

**Comment by Filostorm** [comment]
Awesome, that's much better!
