### ISSUE TITLE
Crashing with Rubidium Mod

### ISSUE THREAD

**Issue by Kaiju007** [SammySemicolon/Malum-Mod#148]
Hello,

so I played Malum and had a lot of other Mods Installed
what I found out was that every time a Particle was Rendert for the Souls you Harvest, your Game just Dies.
that because i had Rubidium installed as a Substitude for Optifine.
so when i turn off the Particle effects and kill a Mob that Drops the Souls,
 then you dont Crash

Crashlog looks like this:
[crash-2022-10-28_01.36.31-client.txt](https://github.com/SammySemicolon/Malum-Mod/files/9883719/crash-2022-10-28_01.36.31-client.txt)

i cant quite figure out why its just when Rubidium is Installed but i hope it is Fixable
or maybe it could help to put a option in the Configs to Turn of those particle

**Comment by SammySemicolon** [comment]
You can go to lodestone-client and turn off particle buffering.
