### ISSUE TITLE
Doesn't work with rei, seems to require jei

### ISSUE THREAD

**Issue by FearAK** [SammySemicolon/Malum-Mod#149]
Tried to switch from using jei to rei and suddenly the game crashes and says something about malum and jei.
[latest.log](https://github.com/SammySemicolon/Malum-Mod/files/9960981/latest.log)

**Comment by SammySemicolon** [comment]
Could you post the crash log?

**Comment by FearAK** [comment]
[crash-2022-11-08_12.38.01-fml.txt](https://github.com/SammySemicolon/Malum-Mod/files/9961065/crash-2022-11-08_12.38.01-fml.txt)

**Comment by Filostorm** [comment]
Same issue. Any chance we could get REI support?

**Comment by EpicSquid** [comment]
It should work with the addon for providing rei support using jei adapters. At least in testing this has worked for me. Not sure what the issue is

**Comment by Filostorm** [comment]
Yeah it does. I was testing with some other stuff at the same time and mistakenly assumed I didn't need the plug-in.

**Comment by EpicSquid** [comment]
Awesome, thanks for checking!
