### ISSUE TITLE
Not getting any spirit drops

### ISSUE THREAD

**Issue by Morilli** [SammySemicolon/Malum-Mod#15]
I was just trying to get into this mod now, and I'm stuck on getting spirits. As far as I understand it, killing mobs with the scythe should drop spirits, right? Because I have not gotten a single spirit drop so far.

Could this be some cross-mod incompatibility? I know there are lots of other mob-changing mods on this server, but I don't feel like having other mods installed should ever break stuff in this way.

**Comment by SammySemicolon** [comment]
If you're on the latest latest version you should be fine, there was a bug in some old version where mobs refused to drop spirits.

**Comment by Morilli** [comment]
I can definitely confirm that I am on version `0.3.0`.

**Comment by Morilli** [comment]
Not sure what to test this with other than to take out mod for mod and create new worlds and wait for forge to load until I can identify the cause. So far I can say that ghasts seed to drop spirits, but everything else I've tested with does not.

**Comment by SammySemicolon** [comment]
Rlly weird, I'll be closing the issue since spirit drops got quite an internal redo in the indev version, it's a json based system now. If the issue persists past the update then feel free to reopen.

**Comment by Morilli** [comment]
Seems the issue lies in [this mod](https://www.curseforge.com/minecraft/mc-mods/my-hero-academia). Not sure which side is responsible but having had issues with that other mod before I'd assume you're fine.
