### ISSUE TITLE
Ortus Namechange - Lodestone

### ISSUE THREAD

**Issue by Moomsy** [SammySemicolon/Malum-Mod#151]
Heya i just wanted to let you know that in your mods.toml Lodestone is still mentioned as Ortus which makes it very hard to combine the mod with others that use Lodestones newer versions without the manual configuration. 

Other than that no issues accuring. Would be good if you would just change the Dependency to make it easier for Modpack Devs. 

tyvm and have a gooden ^^

**Comment by SammySemicolon** [comment]
![image](https://user-images.githubusercontent.com/69329424/200666184-c298934f-0009-48b3-bb63-b9e360045663.png)
It ain't so :P

**Comment by Moomsy** [comment]
i mean i just changed it manually myself from ortus to lodestone, maybe CF didnt give me the latest version then :)

**Comment by Moomsy** [comment]
and yes i have to say - CF just refused to give me the latest :)
