### ISSUE TITLE
Natural quartz generation config mislabeled 

### ISSUE THREAD

**Issue by Tyrus5255** [SammySemicolon/Malum-Mod#152]
I'm developing a pack and I use a separate mod to adjust ore spawning,

I wanted to disable the generation of natural quartz ore, since I wanted it to be gated behind the nether. When I went to change it in the config I noticed that the config for toggling natural quartz is incorrectly stated as the same config for enabling and disabling brilliant stone. 

![image](https://user-images.githubusercontent.com/32311201/204106568-c18fcfc7-b70a-4a13-bb7d-fd26b3047cf1.png)
 
the config still functions as intended, leaving brilliant stone to generate, while disabling natural quartz from spawning as an ore, and still allowing for natural quartz geodes to generate.

**Comment by EpicSquid** [comment]
Fixed in dev at least, will go out in a future release
