### ISSUE TITLE
[1.18.2] Mod requesting a dependency that doesn't exist

### ISSUE THREAD

**Issue by vizthex123** [SammySemicolon/Malum-Mod#154]
Malum wants a mod called "Ortus" to load, but that mod doesn't exist. Lodestone shows up when I google "Ortus", but that doesn't seem to be the correct mod.

Disabling or removing Malum fixes the issue. Updating Malum to Beta 1.4.3.1 fixes the crash.

Log: [latest.log](https://github.com/SammySemicolon/Malum-Mod/files/10241143/latest.log)

**Comment by EpicSquid** [comment]
Ortus is the old name for the library mod lodestone. By default the launcher downloads the latest release of lodestone but not the beta of malum, meaning it gets a version that is now named lodestone but with older malum that depends on ortus. Just use the beta instead.

**Comment by vizthex123** [comment]
I am, but you should mark it as a release so others don't encounter this issue.
