### ISSUE TITLE
Mod requires "ortus" but ortus is nowhere to be found

### ISSUE THREAD

**Issue by pikachu12999** [SammySemicolon/Malum-Mod#155]
whenever i try and launch minecraft with malum it says another mod "ortus" is required, but i cannot find this mod anywhere, i haven't seen any mention of this mod at all, can someone shed some light on this?
![Screenshot 2022-12-20 002251](https://user-images.githubusercontent.com/121079211/208590158-e973e10a-812e-4215-ad0c-5474e884bb41.jpg)

**Comment by EpicSquid** [comment]
Ortus was renamed to lodestone. Just switch to using the latest beta of malum.
