### ISSUE TITLE
[1.18.2] Void Conduits crash 

### ISSUE THREAD

**Issue by LunafeyLazuli** [SammySemicolon/Malum-Mod#159]
[Beeg_crash (1).txt](https://github.com/SammySemicolon/Malum-Mod/files/10473449/Beeg_crash.1.txt)

malum-1.18.2-1.4.4.jar
Forge 40.2.0

**Comment by SammySemicolon** [comment]
This is basically the same issue as the previous one, so I'll be closing it. Also I like ur avatar here and I'm almost certain I know the artist.

**Comment by LunafeyLazuli** [comment]
Haha no worries! And tbh I can't remember where I found it, may have been a google search or something, but it's super cute XD
