### ISSUE TITLE
Suggestion: Upgraded Scythe

### ISSUE THREAD

**Issue by Fortist** [SammySemicolon/Malum-Mod#16]
Im currently running with a scythe and it feels much weaker than It should, due to my own mod pack.
Im unsure if there are other spirit gathering weapons like it, but Im working on the Awakened Tyrwhatever.
So Im suggesting an upgraded scythe using the ingots in the mod or maybe a Curio item that allows you to gather spirit shards with any weapon.

Though also, It isnt marked as a sword so some sword enchantments from other mods dont work with it, which kinda sucks when I want to have a single overpowered weapon and it would be great to also be collecting spirits with it.

Edit: Oh and also re-colorable ether, made a color I didnt really care for and I cant switch it to another. 
Though Ill probably do this myself.

**Comment by SammySemicolon** [comment]
I'm unsure why you can't recolor your ether, if you're in the latest version it should work just fine. 
In the indev version I've made an upgrade to the scythe, even more scythe related stuff is coming too <3

**Comment by Fortist** [comment]
Im unsure why either, but a few .json files later it's fine.
