### ISSUE TITLE
[1.18.2] Rites client crash

### ISSUE THREAD

**Issue by LunafeyLazuli** [SammySemicolon/Malum-Mod#160]
[crash-2023-01-21_18.23.23-client.txt](https://github.com/SammySemicolon/Malum-Mod/files/10473450/crash-2023-01-21_18.23.23-client.txt)

malum-1.18.2-1.4.4.jar
Forge 40.2.0

**Comment by SammySemicolon** [comment]
What version of lodestone are you using

**Comment by LunafeyLazuli** [comment]
Oops forgot to post that, my bad! lodestone-1.18.2-1.3.jar

**Comment by LunafeyLazuli** [comment]
Update: looks like my friend that was having the crash did indeed not update their lodestone like I told them too XD sorry to bother you sammy!
