### ISSUE TITLE
Broken texture in latest update(1.4.4)

### ISSUE THREAD

**Issue by NotAPotter** [SammySemicolon/Malum-Mod#161]
The Amulet of Gratitude only puts a large broken texture on the player model.

**Comment by SammySemicolon** [comment]
The token only renders something for mod devs or patreons. If I am to help here, I'd need to know who you are.

**Comment by NotAPotter** [comment]
Makes sense. I'm WholeHogg in the game and Howard Murphy on Patreon.

**Comment by SammySemicolon** [comment]
Hello, I apologize for that. I hope it's not a problem in ur eyes.
I released a version which fixes this, here you go: https://www.curseforge.com/minecraft/mc-mods/malum/files/4362772
