### ISSUE TITLE
1.18.2 Dedicated server crash mixins compat

### ISSUE THREAD

**Issue by Proxwian** [SammySemicolon/Malum-Mod#162]
Looks like Perfomant mod incompatibility. Since beta version of Perfomant is patreon-distributing-only, I can't provide jar file for you, but hope some logs may help.

[latest.log](https://github.com/SammySemicolon/Malum-Mod/files/10487129/latest.log)

Also reported to Perfomant mod dev Discord server. Be aware that pervious stable version of Malum works well with Perfomant.

**Comment by yrsegal** [comment]
Could you see if you could get us the mixin from Performant that mixes into LivingEntity? that's the only bit of code we'd need to see

**Comment by Proxwian** [comment]
![Uploading FA67B776-AE1B-4C8F-A619-73E69105062D.jpeg…]()

**Comment by Proxwian** [comment]
![Uploading A8CF33D7-4A5C-438E-A32F-0594AC3A290B.jpeg…]()

**Comment by Proxwian** [comment]
![telegram-cloud-photo-size-2-5368812599103309924-y](https://user-images.githubusercontent.com/31781674/214338521-abdf6a24-5544-496e-8b7f-19887aadb976.jpg)

**Comment by Proxwian** [comment]
Please. my server is literally dying without Perfomant(

**Comment by someaddons** [comment]
> Could you see if you could get us the mixin from Performant that mixes into LivingEntity? that's the only bit of code we'd need to see

Like I said before, it probably makes more sense to use the gravity entity attribute forge explicitly added for adjusting entities gravity, the mixin I'm using is actually very simple:

```
    @Redirect(method = "travel", at = @At(value = "INVOKE", target = "Lnet/minecraft/world/level/Level;getFluidState(Lnet/minecraft/core/BlockPos;)Lnet/minecraft/world/level/material/FluidState;"))
    private FluidState onTravelGetFluidState(Level world, BlockPos pos)
    {
        return getCache().getFluidState(pos);
    }

**Comment by SammySemicolon** [comment]
> Please. my server is literally dying without Perfomant(

It'll be a while if it wasn't obvious already. I'm quite busy as of late :(

**Comment by SammySemicolon** [comment]
Should be fixed now !!!!!!

**Comment by SammySemicolon** [comment]
Actually nvm I quite literally didn't fix it nvm

**Comment by katubug** [comment]
Same issue, except 1.19.2 forge

**Comment by EpicSquid** [comment]
Gimme a few days and I'll see if I can sort this, seems like the kind of low hanging fruit i can get behind

**Comment by SammySemicolon** [comment]
Fixed as of https://github.com/SammySemicolon/Malum-Mod/commit/83141cce82b08da10fbefe9d8de13da33bfeee72
Thank u for being patient with me.
