### ISSUE TITLE
"itemIdRegex" of spirit repair recipes not working

### ISSUE THREAD

**Issue by Pet-Slime** [SammySemicolon/Malum-Mod#164]
Mod List:

- lodestone-1.18.2-1.3
- malum-1.18.2-1.4.4.2
- JustEnoughResources-1.18.2-0.14.1.171
- jei-1.18.2-forge-10.2.1.1002
- curios-forge-1.18.2-5.0.7.1

[18:16:03] [Render thread/INFO] [minecraft/RecipeManager]: Skipping loading recipe malum:spirit_crucible/repair/gold as it's serializer returned null

as well for the other items that use the itemIDRegex.

**Comment by SammySemicolon** [comment]
uh oh :sob:

**Comment by SammySemicolon** [comment]
Fixed
