### ISSUE TITLE
[1.18.2] Agender prideweave shares recipe with Aro prideweave

### ISSUE THREAD

**Issue by moon-st0ne** [SammySemicolon/Malum-Mod#165]
Aro prideweave is the correct recipe, Agender is the broken one.
On 1.18.2-1.4.4.3
![image](https://user-images.githubusercontent.com/29065768/215960943-81c5e3b1-611e-4911-99ff-0cdf676c3c5f.png)

**Comment by SammySemicolon** [comment]
What does this mean? Are they conflicting? Is one absent? What's up

**Comment by moon-st0ne** [comment]
They have the same recipe. The "Arrow" prideweave is the correct pun I imagine. So it's a recipe conflict, because the agender one presumably shouldn't be an arrow.
![image](https://user-images.githubusercontent.com/29065768/215966237-728f7789-c656-4a06-b681-d3fb98deece1.png)
