### ISSUE TITLE
[1.18.2] Aroace Prideweave does not work

### ISSUE THREAD

**Issue by moon-st0ne** [SammySemicolon/Malum-Mod#166]
Tested on version 1.4.4.3.
All of the prideweaves (and the ancient weave) work except for the Aroace prideweave. The item just swaps with the armor piece on the pedestal instead of applying.
[Video here](https://dl.dropboxusercontent.com/s/50mnt6j734zzsgy/javaw_MWRgP2mnhx.mp4)

**Comment by SammySemicolon** [comment]
Fixed, stupid god damn recipe refusing to cooperate.
