### ISSUE TITLE
Custom Recipes

### ISSUE THREAD

**Issue by Drakoflame** [SammySemicolon/Malum-Mod#167]
If they're possible, How do we add them?

I'm working on a private modpack and would love to make Malum a bit more of a focus in the pack, and I'd love to add some custom recipes for some items, but I'm not sure if/how to add said recipes.

Is there documentation somewhere, or should I just dig into the source and look at how the current recipes are done and try to replicate it with a datapack?

**Comment by SammySemicolon** [comment]
There is no documentation quite yet, you can message me privately on my discord and we can talk :) Sammy;#0411

**Comment by Drakoflame** [comment]
Will do! Request sent (Renay#5840

**Comment by SammySemicolon** [comment]
Don't think I got it-
