### ISSUE TITLE
[1.18.2] Runewood Tree generation crash.

### ISSUE THREAD

**Issue by Gbergz** [SammySemicolon/Malum-Mod#169]
Title^

Generating a world then running around until I think a Runewood tree spawns, server crashes.

Versions:
MC 1.18.2
Forge: 40.2.0
Malum: 1.4.3.1, this happens with the latest version aswell (1.4.4.3), downgraded to this as I thought it would fix it. It did not.

Crash-Report: https://gist.githubusercontent.com/Gbergz/5b1e627ba94a36d9b1cf0d53d06e47ad/raw/8984dc1af269352fe89ae13a4fada18afefd50d1/gistfile1.txt

Not sure what changed elsewhere as this wasn't an issue on the old version before, but all of a sudden it crashes.

**-** Gbergz

**Comment by SammySemicolon** [comment]
It took me some time to reply, but I believe this is an issue that's basically just "your lodestone version is outdated"
