### ISSUE TITLE
Suggestion: Custom Recipes?

### ISSUE THREAD

**Issue by Fortist** [SammySemicolon/Malum-Mod#17]
I use a lot of mods and I have ideas for cross mod crafting/using and some recipes I may want to tweak a bit to use tags and the like.
Im not asking for something like crafttweaker support, _unless_ thats the only way to interact with the Rune Table or Spirit Altar.
Or Kubejs. But straight datapack support is fine.

**Comment by SammySemicolon** [comment]
In the indev version this is already the case, spirit drop rules have been converted to spirit loot tables with json, and the spirit altar's recipe system is based off of json.
