### ISSUE TITLE
1.18.2 Client crash when i open the Malum book

### ISSUE THREAD

**Issue by Silverseppel** [SammySemicolon/Malum-Mod#171]
HI,
when i want to open the malum manual the client crashes under the server only shows that i have left the server.

[https://pastebin.com/PfY1sx4q](url)

**Comment by QinomeD** [comment]
I will fix (I don't want to touch it, but if I have to...)

**Comment by SammySemicolon** [comment]
This is an issue with the Metallum addon, either wait for an update or remove the mod.
