### ISSUE TITLE
[Translation][1.18.2]1.4.4.3 zh_cn traslation update

### ISSUE THREAD

**Issue by 6371peter** [SammySemicolon/Malum-Mod#172]
MOD Version:1.18.2-1.4.4.3

[zh_cn.zip](https://github.com/SammySemicolon/Malum-Mod/files/10852634/zh_cn.zip)

**Comment by SammySemicolon** [comment]
A more recent and up-to-date translation was submitted via pull request. I'm sorry for never getting around to this one !!! I apologize.
