### ISSUE TITLE
poseidons_grasp texture name named poseidons_grip Typo

### ISSUE THREAD

**Issue by Shibva** [SammySemicolon/Malum-Mod#174]

**Comment by SammySemicolon** [comment]
I am aware of the missing texture yeah

**Comment by Shibva** [comment]
what the hell?; I dint even...

**Comment by Shibva** [comment]
well I found the issue

![image](https://user-images.githubusercontent.com/38770780/223846036-dc02a838-51f2-41e7-9fdf-be2b7ceac847.png)

**Comment by Shibva** [comment]
its named Grip instead of Grasp

**Comment by Shibva** [comment]
and digging though the code it refers to it as grasp

error is a result of a typo

**Comment by Shibva** [comment]
replacing it wtih grasp should fix it

**Comment by Shibva** [comment]
![poseidons_grasp](https://user-images.githubusercontent.com/38770780/223846553-02947f40-1e3c-4eb8-9179-42703736005f.png)
there ya go

because the code registered it as poseidons_grasp; it doesn't recognize poseidons_grip

this simple rename will fix it.

tbh glad I found this on my own

Edit: damnit it dint save the file name as is
Its the same file but renamed poseidons_grasp instead of poseidons_grip

**Comment by SammySemicolon** [comment]
The problem is more so that I don't like the texture, but can't seem to make anything better. 
But I suppose I might as well just use it for now.

**Comment by Shibva** [comment]
would you be open to someone possibly making a new texture for it?
