### ISSUE TITLE
[1.18.2] Malum crashes on launch, currently unusable.

### ISSUE THREAD

**Issue by Warhand** [SammySemicolon/Malum-Mod#176]
MC version: 1.18.2
Forge version: 40.2.0 & 40.2.1
Malum version: 1.4.4.3
Lodestone: 1.4
Curios API: 5.0.9.0

On launch the game attempts to load, and then crashes, citing a blames InvocationTargetException with a value of null. No other information is given, and this issue occurs even if all other mods are removed aside from Malum and its dependencies.

Latest.log: https://gist.github.com/Warhand/c3ca13effad499906ea5f2954e4bf043
Crash report: https://gist.github.com/Warhand/714bb7f21770e869cf48c1d22fd4045c

**Comment by SammySemicolon** [comment]
Use lodestone 1.3
