### ISSUE TITLE
1.18.2 crash with no other mods

### ISSUE THREAD

**Issue by JuanLeGuetteur** [SammySemicolon/Malum-Mod#178]
The game crashes whenever the mod is installed, even along only dependencies on a fresh Windows 11 installation. 
[latest.log](https://github.com/SammySemicolon/Malum-Mod/files/11373763/latest.log)

**Comment by ElysiaSilly** [comment]
downgrade lodestone to 1.3

**Comment by festro** [comment]
Thanks, that fixed it for me, still has compatibility issues for me but that's beyond the scope of this post.
