### ISSUE TITLE
Crash on Runewood Sap Gather

### ISSUE THREAD

**Issue by AefRal** [SammySemicolon/Malum-Mod#180]
Playing on FragmentCraft modpack.
I drank a bottle of Ars Nouveau's Mana Regen to free up a bottle.
Then I stripped a runed log to expose the sap.
The very second I right-clicked to collect it, the window closed straight to desktop!
This was the error file with code -1073740940.
[hs_err_pid11036.log](https://github.com/SammySemicolon/Malum-Mod/files/11522383/hs_err_pid11036.log)
I had since updated Malum from 1.3.4 to 1.4.4.3, and now the pack won't even start.

**Comment by SammySemicolon** [comment]
I have no idea what this error even means. if this pops up again for anyone feel free to re-open the issue.
