### ISSUE TITLE
(1.5) Servers do not start

### ISSUE THREAD

**Issue by MrFastZombie** [SammySemicolon/Malum-Mod#183]
Forge 40.2.4 (also tested on 40.2.0)
Malum 1.5
Lodestone 1.4

So obviously since 1.5 is not officially out: this is with a self-compiled build, and I realize that the build is probably not yet complete. I am reporting this because I figure that this might be easy to miss since it only affects servers. 

My friend decided to try compiling the latest 1.5 source and we found that while the client works fine, servers cannot start due to a `java.lang.NoClassDefFoundError: net/minecraft/client/model/HumanoidModel` error.

Just before the error, it shows this Lodestone error:

`[29May2023 15:19:46.805] [modloading-worker-0/ERROR] [net.minecraftforge.eventbus.EventSubclassTransformer/EVENTBUS]: Could not find parent net/minecraft/client/model/HumanoidModel for class team/lodestar/lodestone/systems/model/LodestoneArmorModel in classloader cpw.mods.modlauncher.TransformingClassLoader@14ef2482 on thread Thread[modloading-worker-0,5,main]`

This was tested on a server with just Malum, Lodestone, and Curios. The issue only occurs with Malum installed.

full log: https://mclo.gs/K0wR2UV

**Comment by SammySemicolon** [comment]
Yeah I only do server-bugfixes right before a release. Sorry

**Comment by MrFastZombie** [comment]
Fair enough, just wanted to make sure you were aware.

**Comment by SammySemicolon** [comment]
Pretty sure what the issue is here too, I rewrote how armor skins work and yeah.

**Comment by SammySemicolon** [comment]
Fixed it up
