### ISSUE TITLE
1.18.2 Game Crashes with the newest version of Create

### ISSUE THREAD

**Issue by CaioBongs** [SammySemicolon/Malum-Mod#184]
From what i understand has something to do with the potato launcher from Create, i'll leave the crash report here hope it helps
[crash-2023-05-31_12.13.30-server.txt](https://github.com/SammySemicolon/Malum-Mod/files/11618513/crash-2023-05-31_12.13.30-server.txt)

**Comment by SammySemicolon** [comment]
Yeah, already fixed, just need to push out a release.

**Comment by ElysiaSilly** [comment]
necromancing this
seem to be having the same issue on 1.19.2
[crash-2023-07-12_00.37.03-server.txt](https://github.com/SammySemicolon/Malum-Mod/files/12021965/crash-2023-07-12_00.37.03-server.txt)
