### ISSUE TITLE
[TNP Limitless 5] Crash Upon Bonemealing Runewood Sapling

### ISSUE THREAD

**Issue by SaturdayHS** [SammySemicolon/Malum-Mod#185]
I crashed while trying to bonemeal a Runewood Sapling, the Pastebin is posted below. After loading up the pack and getting into the world, there was a crazy amount of lag which I thought was related to worldgen and crashed again, Pastebin for that is also posted below.

_Bonemeal crash log: [https://pastebin.com/meYirGTt](url)_

_'Worldgen' crash log: [https://pastebin.com/BN4FT0x8](url)_

**Comment by SammySemicolon** [comment]
This was ages ago sorry !!! I'm pretty sure you just had an outdated lodestone version.
