### ISSUE TITLE
Create Compat issue

### ISSUE THREAD

**Issue by border999** [SammySemicolon/Malum-Mod#186]
https://gist.github.com/border999/0d4df874efa15b2617577cfcf6d28eb1
malum-1.18.2-1.4.4.3
lodestone-1.18.2-1.3
create-1.18.2-0.5.1.b

**Comment by ZestyBlaze** [comment]
It's a known issue due to breaking Create changes that broke all addons and compat. Sammy has pushed a fix and he just needs to upload it. Check #184
