### ISSUE TITLE
java.lang.reflect.invocationtargetexception 

### ISSUE THREAD

**Issue by Bell969** [SammySemicolon/Malum-Mod#188]

**Comment by ZestyBlaze** [comment]
Crash log?

**Comment by coldloaded** [comment]
same thing here
malum 1.4.4.3 and lodestone 1.4 are installed


> [15:58:10] [modloading-worker-0/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: malum, class com.sammy.malum.MalumMod
> java.lang.reflect.InvocationTargetException: null
> 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
> 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
> 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.2.0.jar%23150!/:?] {}
> 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.2.0.jar%23149!/:?] {re:mixin}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?] {}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?] {}
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] {}
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] {}
> 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] {re:mixin,re:computing_frames}
> 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] {re:mixin,re:computing_frames}
> 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?] {re:mixin}
> Caused by: java.lang.NoClassDefFoundError: team/lodestar/lodestone/systems/rendering/particle/screen/emitter/ItemParticleEmitter
> 	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {}
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:116) ~[securejarhandler-1.0.3.jar:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?] {}
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
> 	at com.sammy.malum.MalumMod.<init>(MalumMod.java:55) ~[malum-1.18.2-1.4.4.3.jar%23109!/:1.18.2-1.4.4.3] {re:classloading}
> 	... 14 more
> Caused by: java.lang.ClassNotFoundException: team.lodestar.lodestone.systems.rendering.particle.screen.emitter.ItemParticleEmitter
> 	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
> 	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {}
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:116) ~[securejarhandler-1.0.3.jar:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?] {}
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
> 	at com.sammy.malum.MalumMod.<init>(MalumMod.java:55) ~[malum-1.18.2-1.4.4.3.jar%23109!/:1.18.2-1.4.4.3] {re:classloading}
> 	... 14 more

**Comment by coldloaded** [comment]
malum 1.3.7 with ortus have loaded successfully

**Comment by Chaos02** [comment]
`Exception message: java.lang.ClassNotFoundException: team.lodestar.lodestone.systems.rendering.particle.screen.emitter.ItemParticleEmitter`
...only logical since there is no such class in [src/main/java/team/lodestar/lodestone/systems/rendering](https://github.com/LodestarMC/Lodestone/tree/4d10134f860b8fe49170018a2bb7a3698ba3b310/src/main/java/team/lodestar/lodestone/systems/rendering)...
I believe, it has been moved into somewhere here [src/main/java/team/lodestar/lodestone/systems/particle/screen](https://github.com/LodestarMC/Lodestone/tree/4d10134f860b8fe49170018a2bb7a3698ba3b310/src/main/java/team/lodestar/lodestone/systems/particle/screen)

**Comment by SammySemicolon** [comment]
It was a problem with them using lodestone 1.4 rather than 1.3 alongside malum. Malum 1.5 will no longer complain about latest lodestone
