### ISSUE TITLE
[1.18.2] Game doesn't load

### ISSUE THREAD

**Issue by vizthex123** [SammySemicolon/Malum-Mod#189]
Gives me this error screen:
![image](https://github.com/SammySemicolon/Malum-Mod/assets/31721920/a9dbd8f8-42eb-4e60-ad3e-c9d7ea41690c)

Latest version of Malum (1.4.4.3), Lodestone (1.4) and Forge installed (40.2.9)

Log:
[latest.log](https://github.com/SammySemicolon/Malum-Mod/files/11891358/latest.log)

**Comment by SammySemicolon** [comment]
Lodestone 1.4 didn't work with the latest version of malum, Malum 1.5 will no longer complain about Lodestone 1.4

**Comment by vizthex123** [comment]
noice, thanks for fixing it.
