### ISSUE TITLE
Bug: Uncollectable Spirit Shards

### ISSUE THREAD

**Issue by Fortist** [SammySemicolon/Malum-Mod#19]
So, I kill a mob and spirit shards come out, but I die in the process.
When I return to said FLOATING shards, they continue to float.
This also happens when I crash on a kill and when I return the shards continue to float.

I am unsure if this happens when I changed dimensions as well.
As far as I know, there doesnt seem to be a despawn timer on these floating version of the shards, as I spend a good chunk of time doing other things and the shards are still there floating.

In that same vein, shards sometimes float INTO/through blocks, and with the above bug it seems that I have entities that I cannot find just sitting there (Xaero's minimap shows them still there)

**Comment by SammySemicolon** [comment]
In the indev version (1.0 release) spirits have an actual despawn timer + gain lots of range if stuck in a block.

**Comment by hron84** [comment]
@SammySemicolon when do you plan to release this fix? My base has a lot of uncollectable crystal entities and it's very annoying.

Also, could you provide a command to force clean up these crystals?

**Comment by strangeoddity** [comment]
Is it possible to fix this in 1.16.5? Malum is in ATM Spellbound, and has this problem.
