### ISSUE TITLE
[1.18.2] Crash when attacking

### ISSUE THREAD

**Issue by vizthex123** [SammySemicolon/Malum-Mod#190]
Malum and Create are mentioned in the log, but I've had issues with this mod before so I'm posting it here.

Log:
[latest.log](https://github.com/SammySemicolon/Malum-Mod/files/11898678/latest.log)

**Comment by SammySemicolon** [comment]
I don't even know how u got in the game, right now iirc create and malum are just incompatible

**Comment by SammySemicolon** [comment]
Fixed in 1.5
