### ISSUE TITLE
More Create compat issues. - Create crushed ore ID's changed, breaking compat recipes.

### ISSUE THREAD

**Issue by Warhand** [SammySemicolon/Malum-Mod#193]
Certain create compat recipes that used crushed ores no longer work, because create changed their naming format from "create:crushed_iron_ore" to "create:crushed_raw_iron"

The main issue I see at a glance is that the rare earths crushing recipe doesn't produce any outputs, because all of its potential outputs are ID's that are no longer in use.

**Comment by SammySemicolon** [comment]
Should be fixed !!!
