### ISSUE TITLE
Crash in a Server when do 5 arcanus spirit totem

### ISSUE THREAD

**Issue by YamiKnigth** [SammySemicolon/Malum-Mod#194]
When I perform the ritual with the totem of 5 arcane spirits in runewood, the server immediately crashes and gives me this error.

[crashReport2.txt](https://github.com/SammySemicolon/Malum-Mod/files/11970069/crashReport2.txt)

**Comment by SammySemicolon** [comment]
Fixed in 1.5.0.1
