### ISSUE TITLE
When player  jump on weeping_well it bugs 1.18.2 archligth.

### ISSUE THREAD

**Issue by YamiKnigth** [SammySemicolon/Malum-Mod#195]
When a player enters weeping_well, it bugs and no longer allows him to enter the server, the stack trace would be as follows.
[stackTraceMalumTransmut.txt](https://github.com/SammySemicolon/Malum-Mod/files/11986676/stackTraceMalumTransmut.txt)

**Comment by SammySemicolon** [comment]
This is just another serverside particle crash, it's already fixed on the dev branch, but I found some rendering issues I'd like to fix first before releasing anything.

**Comment by YamiKnigth** [comment]
thank you so much, we can wait for it i hope doesn't take too much. I opened another issue with a detail with a totem, I don't know if it is also identified.
'Crash in a Server when do 5 arcanus spirit totem #194'

**Comment by SammySemicolon** [comment]
Yeah these are all the same issue.

**Comment by SammySemicolon** [comment]
Fixed in 1.5.0.1
