### ISSUE TITLE
crash in modified ATM 8 modpack

### ISSUE THREAD

**Issue by pibblepower** [SammySemicolon/Malum-Mod#196]
So, I just downloaded the new 1.19.2 version of malum, and added it to my ATM modpack (which i have modified a good deal). I log into my world, and I crash almost immediately. Does anyone know what's happening? Here's the crash report:
[crash-2023-07-11_09.56.17-server.txt](https://github.com/SammySemicolon/Malum-Mod/files/12021615/crash-2023-07-11_09.56.17-server.txt)

**Comment by SammySemicolon** [comment]
It's a create compatibility issue. We'll be posting an updated jar sometime today that fixes this.

**Comment by SammySemicolon** [comment]
Fixed, download latest !!!
