### ISSUE TITLE
Incompatibility between Malum/Lodestone and Superior Shields

### ISSUE THREAD

**Issue by neutralboolean** [SammySemicolon/Malum-Mod#198]
Got this error when I tried to start a new world with this combination. I confirmed that the world loads fine if I create one with just Superior Shields and the Lodestone library.
https://pastebin.com/KT58aRkp

**Comment by EpicSquid** [comment]
Damnit, gimme a day and I'll have this sorted on the superior shields side

**Comment by neutralboolean** [comment]
No worries. Thanks for the quick response

**Comment by EpicSquid** [comment]
Fixed, just waiting for upload https://legacy.curseforge.com/minecraft/mc-mods/superior-shields/files/4644481
