### ISSUE TITLE
Enchantment Descriptions Support

### ISSUE THREAD

**Issue by WenXin20** [SammySemicolon/Malum-Mod#2]
- Support for this mod would only require `enchantment.malum.enchant_name.desc` to be added to the lang file.
- Mod link: https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions

**Comment by SammySemicolon** [comment]
![image](https://user-images.githubusercontent.com/69329424/119310602-41216a00-bc70-11eb-839a-d801882238ff.png)
Thank you for reminding me~! <3
