### ISSUE TITLE
Scythe in offhand still generates spirit drops

### ISSUE THREAD

**Issue by Morilli** [SammySemicolon/Malum-Mod#20]
As title. Having the scythe in the offhand still generates all spirit drops on kill as normal, even when attacking with a completely different weapon. Don't think this is supposed to work this way.

**Comment by SammySemicolon** [comment]
This is actually by choice! I think little bugs that allow the player to outsmart the system and gain an advantage are just fine. Once more ways of harvesting spirits are in the mod then I'll look into fixing it <3.
