### ISSUE TITLE
1.18.2 Crash

### ISSUE THREAD

**Issue by tazzy989** [SammySemicolon/Malum-Mod#201]
https://paste.atlauncher.com/view/f88d12d2-96bf-4249-84b5-17ef9de08550

I can't tell from the logs what's not playing nice. I'm not great at reading logs though. The instance never loads, it just goes straight to an error screen and says "malum has failed to load correctly." 

Lmk if there's a way I can fix this or if I'm simply missing something obvious. :) It's a pretty large, haphazardly thrown together modpack for me and a friend.

**Comment by SammySemicolon** [comment]
Make sure both lodestone and malum are the latest version !!!

**Comment by tazzy989** [comment]
malum-1.18.2-1.4.4.3.jar
lodestone-1.18.2-1.4.jar

Are these the most recent versions for 1.18.2? These are what's listed in the logs above.

**Comment by SammySemicolon** [comment]
malum 1.5.0.2 is latest
lodestone 1.4.2 is latest
