### ISSUE TITLE
[1.18.2] Crash when using runewood totem

### ISSUE THREAD

**Issue by Proxwian** [SammySemicolon/Malum-Mod#203]
Crash on dedicated server, latest malum and lodestone.

[crash-2023-07-30_13.23.32-server.txt](https://github.com/SammySemicolon/Malum-Mod/files/12209291/crash-2023-07-30_13.23.32-server.txt)

**Comment by Proxwian** [comment]
Can make temporary fix by commenting lines ActiveBlightEvent.java:64-65

**Comment by SammySemicolon** [comment]
1.16.5/1.18.2/1.19.2 is no longer supported

**Comment by Proxwian** [comment]
Bruh that ticket was almost year ago, when it was
