### ISSUE TITLE
1.19.2 create+malum

### ISSUE THREAD

**Issue by Chugunol** [SammySemicolon/Malum-Mod#204]
game crashes when you try to punch anything with both create and malumm installed. I tried malum-1.19.2-1.5.0.1.jar and different versions of create- same results
[crash-2023-08-01_16.56.11-server.txt](https://github.com/SammySemicolon/Malum-Mod/files/12230025/crash-2023-08-01_16.56.11-server.txt)

**Comment by SammySemicolon** [comment]
use malum 1.5.0.2
