### ISSUE TITLE
Crashes when a player enters server

### ISSUE THREAD

**Issue by KizzerMo** [SammySemicolon/Malum-Mod#205]
[crash-2023-08-02_13.56.41-server.txt](https://github.com/SammySemicolon/Malum-Mod/files/12241760/crash-2023-08-02_13.56.41-server.txt)

**Comment by slava110** [comment]
I'm having the same crash. Totems don't seem to save direction in their NBT
![image](https://github.com/SammySemicolon/Malum-Mod/assets/26705162/7c798509-1b19-4fae-af0b-c05a45d0a221)
So when you reload world with active totem (in my case cobblestone generator rite) - it's crashing
Any fix?

**Comment by SammySemicolon** [comment]
1.16.5/1.18.2/1.19.2 is no longer supported

**Comment by SammySemicolon** [comment]
but also I believe I fixed this in the most recent patch for 1.19.2
