### ISSUE TITLE
1.18.2 Crash 

### ISSUE THREAD

**Issue by tazzy989** [SammySemicolon/Malum-Mod#207]
I killed a mob, saw something ethereal flying at me, and the server crashed. Now, upon joining, the server crashes every time. 
https://pastebin.com/x6G1BmTA

The first time it crashed, when I tried to read through the logs, it seemed like ItShallNotTick was not playing nice with it, so we tried removing that. It still crashes unfortunately.

**Comment by SammySemicolon** [comment]
Make sure both lodestone and malum are both the latest version

**Comment by tazzy989** [comment]
Yes, this is the custom pack I created after being told that last time- I updated both to the newest versions I could find on curseforge for 1.18.2.

Sorry for the delayed response again, for some reason I'm not getting emails for notifications ugh

**Comment by SammySemicolon** [comment]
I'm sorry if I like, replied with the same exact "do this" kinda response already to you. To my knowledge the latest version of malum works with the latest version of create for 1.18.2, evidenced by the fact that I am currently running them both simultaneously just fine

**Comment by tazzy989** [comment]
Oh no no, that's fine, I'm sure you get tons of issue threads from people who don't have updated versions installed (like me, the first time I was here, assuming my launcher has installed newest versions.)
Were you able to see anything in the logs? What might Malum not be playing nice with? The only thing that stopped crashing the server was deleting my player profile. Whatever happened like, attached itself to my player. Even being tp'd far from the chunk it happened it didn't make the issue stop. 
The pack has a *lot* of mods 😅

**Comment by SammySemicolon** [comment]
Oh yeah I got this issue mixed up with another one, looking at the log again it's a completely different issue.

**Comment by SammySemicolon** [comment]
The crash happens when the player picks up a spirit, because apparently a helper method in Lodestone doesn't exist.

**Comment by tazzy989** [comment]
Is this something you'll be able to fix on your end? Are spirits just a random drop entity from killing a mob?

**Comment by SammySemicolon** [comment]
Well I can't really replicate this crash at all.
