### ISSUE TITLE
Failing to Initialize Properly [1.18.2] [1.5.0.1]

### ISSUE THREAD

**Issue by CFlatFlat** [SammySemicolon/Malum-Mod#208]
Installed the latest update to fix the crash with Create after updating that, but now Malum fails to initialize whenever I launch my modpack. (Create does as well sometimes, but it does that regardless.)

[crash-2023-08-10_23.41.12-fml.txt](https://github.com/SammySemicolon/Malum-Mod/files/12318497/crash-2023-08-10_23.41.12-fml.txt)
[crash-2023-08-10_23.33.52-fml.txt](https://github.com/SammySemicolon/Malum-Mod/files/12318498/crash-2023-08-10_23.33.52-fml.txt)

**Comment by SammySemicolon** [comment]
Please use the latest version of lodestone, you're currently using 1.3, which malum 1.5 isn't built for

**Comment by CFlatFlat** [comment]
I blame Curseforge for removing the feature where it shows dependencies as you download
