### ISSUE TITLE
Crash when adding a spirit to a runewood on a totem base - Server Crash

### ISSUE THREAD

**Issue by JNCHGTR** [SammySemicolon/Malum-Mod#209]
Hello,

I'd like to report an issue happening in my modpack (Fantasia Adventures).

MC version: 1.16.5
Forge version: 36.2.34
Mod version: 1.16.5-0.3.0

Crash-report: https://gist.github.com/JNCHGTR/84f9a52117ce8c1761715908eb8c0e27

**Comment by SammySemicolon** [comment]
1.16.5/1.18.2/1.19.2 is no longer supported
