### ISSUE TITLE
[1.16.5] Client/Server Sync issue

### ISSUE THREAD

**Issue by drakray** [SammySemicolon/Malum-Mod#21]
NPCs opening doors, and Runewood Sapling growing, are not correctly synced to Client.
Right-clicking or going away/relogging refresh the block.
F3+A(chunk reload) does not fix the problem

Happen on dedicated server, not in local play

**Comment by drakray** [comment]
Also, Spirit entities are invisible

**Comment by drakray** [comment]
Runewood Door are desynced too, visible when Villagers open/close the door
(If you keep a door Open, and a Villager close it, you still see it open but cant pass through)

**Comment by SammySemicolon** [comment]
I haven't been able to replicate this at all, weird!
