### ISSUE TITLE
[1.18.2] Crashed when loading new world (malum:heart_of_stone_strength is invalid)

### ISSUE THREAD

**Issue by PrismaticRose** [SammySemicolon/Malum-Mod#210]
[crash-2023-09-03_12.08.24-client.txt](https://github.com/SammySemicolon/Malum-Mod/files/12506533/crash-2023-09-03_12.08.24-client.txt)

**Comment by SammySemicolon** [comment]
I've no idea why this even happened, it looks like another mod is trying to interact with some malum attributes that have been since removed.

**Comment by PrismaticRose** [comment]
My only thought is maybe attribute fix? But I'm not sure what's causing it, specially on a brand new world

**Comment by PrismaticRose** [comment]
Oh wait, maybe Mobifier? 
at corgitaco.mobifier.common.util.CodecUtil.lambda$createLoggedExceptionRegistryCodec$3(CodecUtil.java:62) ~[Mobifier-forge-1.18.2-1.0.3.jar%23279!/:1.0.3] {re:classloading}
Saw that right under the listed attributes

**Comment by PrismaticRose** [comment]
Figured it out! Just needed to delete the Mobifier config since it still had the old attribute in there when I tried to update xD

**Comment by SammySemicolon** [comment]
There you go !
