### ISSUE TITLE
Void Favor recipe giving wrong output quantity

### ISSUE THREAD

**Issue by AtobaAzul** [SammySemicolon/Malum-Mod#211]
I imagine it's very much wip (On 1.18, at least) but I'd rather report just to be sure

Examples:
Throw in 1 hex ash -> gets returned
Throw in 4 hex ash -> gets turned into 4 void salts 
Throw in 5 hex ash -> gets turned into 5 void salts

The way the recipe is structured [here](https://github.com/SammySemicolon/Malum-Mod/blob/28db31716acec731365d68cd07d9ea8c6de8a08f/src/generated/resources/data/malum/recipes/void_favor/void_salts.json) makes it seem that for every 4 hex ash you throw in you'd get 1 void salts.

**Comment by SammySemicolon** [comment]
Yeah, I suppose I didn't test it. It'll probably lose it's quantity capability anyhow, it makes more sense that way

**Comment by SammySemicolon** [comment]
Fixed in dev version
