### ISSUE TITLE
[1.18.2] World gen error when interacting with GeOre mod

### ISSUE THREAD

**Issue by Eonwe98** [SammySemicolon/Malum-Mod#212]
With MC 1.18.2 when creating a new world with the mod GeOre installed the game will crash. Attached are two logs, first log is using the Cyanide (Forge) mod and the second is the raw log without Cyanide.
[Log-with-Cyanide(Forge).log](https://github.com/SammySemicolon/Malum-Mod/files/12745320/Log-with-Cyanide.Forge.log)
[Log-with-out-Cyanide.log](https://github.com/SammySemicolon/Malum-Mod/files/12745322/Log-with-out-Cyanide.log)

**Comment by SammySemicolon** [comment]
1.16.5/1.18.2/1.19.2 is no longer supported
