### ISSUE TITLE
Greater Runewood Aqueous Rite Crash

### ISSUE THREAD

**Issue by Nihil-theDemiurge** [SammySemicolon/Malum-Mod#213]
Greater Runewood Aqueous Rite crashes the game upon player joining server.

[crash-2023-10-03_10.57.00-server.txt](https://github.com/SammySemicolon/Malum-Mod/files/12789042/crash-2023-10-03_10.57.00-server.txt)

**Comment by SammySemicolon** [comment]
1.18.2/1.19.2 is no longer supported
