### ISSUE TITLE
[1.19.2] Greater Runewood Aqueous Rite dropping dripstone

### ISSUE THREAD

**Issue by rwallac** [SammySemicolon/Malum-Mod#214]
Valhelsia 5: When reading the description for the rite, it seems to say that it makes dripstone drip faster, but what it's doing is causing the dripstone to drop off of the block it's on. 
I'm assuming this isn't intended behavior, as it doesn't seem to do anything useful. 

To reproduce: Make the rite, and place dripstone in the area of the rite. Watch as rite activates and the dripstone falls.

**Comment by SammySemicolon** [comment]
I've no idea why this would be, it's most likely a conflict with some other mod in valhelsia 5

**Comment by SammySemicolon** [comment]
1.18.2/1.19.2 is no longer supported
