### ISSUE TITLE
Crash on trying to render soul shards

### ISSUE THREAD

**Issue by Jackiecrazy** [SammySemicolon/Malum-Mod#22]
I'm not sure why it does this, it only crashes sometimes.
[crash-2021-10-06_13.38.01-client.txt](https://github.com/SammySemicolon/Malum-Mod/files/7296358/crash-2021-10-06_13.38.01-client.txt)

**Comment by Ferret-Master** [comment]
Had the same crash myself, seemed to occur consistently, disabling magnesium solved it so is likely related to it.

**Comment by SammySemicolon** [comment]
See if you can replicate it in 1.18.1 if you've got the time.

**Comment by SammySemicolon** [comment]
Closing issue since 1.16.5 became unsupported.
