### ISSUE TITLE
NullPointerException crash from Totem Base ticking

### ISSUE THREAD

**Issue by CelestialAbyss** [SammySemicolon/Malum-Mod#226]
MC version: 1.19.2
Forge: 43.3.2
Malum version: 1.5.0.3
Lodestone version: 1.4.2

I was not on while players were doing Malum related things, but it might be conflicting with chunk claims from Open Parties & Claims but I'm not too sure.

Edit: It is due to moving the totem base with Carry On, see here: [Discord CDN](https://cdn.discordapp.com/attachments/941621893436424242/1180739395121324084/bandicam_2023-12-02_21-12-40-493.mp4?ex=657e8440&is=656c0f40&hm=f1a476d4f823b6a1e264cfb88a89061362025d7544a44906dbe3d09b29623963&)

Edit 2: It also seems that a server restarting while a totem is in progress also causes the same issue to occur.

Gist is attached here: https://gist.github.com/CelestialAbyss/d058d3774cb6da590437907103da9c75

**Comment by CelestialAbyss** [comment]
Another related crash: https://gist.github.com/CelestialAbyss/98245181190896f4a88ad2bb3e9a6fbc

**Comment by SammySemicolon** [comment]
I'm sorry for not fixing it earlier, life has been a mess and I've had no motivation.
Please try this jar and let me know if it fixes ur issue https://legacy.curseforge.com/minecraft/mc-mods/malum/files/4952075

**Comment by CelestialAbyss** [comment]
I was about to remove your mod in the next modpack update that I was going to publish due to the crashes occurring more and more often with the same cause, but good to see the bug actually patched after being ignored on the Discord after asking about it...

I'll release an update for my players hopefully later today or two days from now and see if my personal server no longer crashes with this.

*More importantly*, take care of yourself first and foremost.

**Comment by CelestialAbyss** [comment]
Okay, it seems like the error has yet to re-occur so it seems fixed... though there's a new issue that *only* happens with Malum's signs.

**Comment by SammySemicolon** [comment]
The malum signs have been a problem for a while, they straight up do not have a proper renderer.
