### ISSUE TITLE
(1.18.2) Ether and Iridescent Ether Torches don't have the minecraft:wall_post_override tag.

### ISSUE THREAD

**Issue by puncrafter** [SammySemicolon/Malum-Mod#228]
Ether and Iridescent Ether Torches don't have the `minecraft:wall_post_override` tag, which makes them look funny when placed on top of walls. Adding the tag to the torches manually via CraftTweaker makes them function as expected.

![2024-01-16_15 00 30](https://github.com/SammySemicolon/Malum-Mod/assets/53954921/fcbd62af-756b-4fa4-bd59-2d53ce2c9fe2)

**Comment by SammySemicolon** [comment]
1.18.2 is no longer supported- fixed just now in 1.20.1
