### ISSUE TITLE
Transmutation with Soulwood Totem not working for most recipes [Plexiglass Mountain]

### ISSUE THREAD

**Issue by ttufts** [SammySemicolon/Malum-Mod#231]
Plexiglass Mountain 1.2.4 - Malum 1.18.2-1.3.7

JEI shows recipes for transmutation using Soulwood totem + arcane rite should convert Runewood -> Soulwood. 

The only transmutation that seems to work is Stone -> Sand, which works quickly and consistently. I'm unable to transmute any Runewood items or saplings. Also tested, Netherrack -> Soul Sand and Soul Sand -> Magma Block, neither work.

**Comment by SammySemicolon** [comment]
1.18.2/1.19.2 is no longer supported
