### ISSUE TITLE
Crash on load in when using EMI

### ISSUE THREAD

**Issue by hauntedminecrafting** [SammySemicolon/Malum-Mod#235]
Hello, 

I was changing over my modpack from using JEI to EMI. It seems like there is a dependency to JEI causing the crash? 

[crash-2024-05-22_05.08.38-client.txt](https://github.com/SammySemicolon/Malum-Mod/files/15401337/crash-2024-05-22_05.08.38-client.txt)

I apologize if I have added something wrong here, it's my first time doing this. Please let me know, if you need any other information or have any questions. 

Thank you for your time and assistance.

**Comment by aking4125** [comment]
You still need JEI. You can use both EMI and JEI together infact, all of the JEI Addons will still function. EMI adds functionally on top of it. 

On the curseforge page, it even reads:

> Runtime JEI Compat: For runtime JEI compat, all you need to do is install JEI alongside EMI and they will work together to share recipes. JEI will be hidden.

**Comment by hauntedminecrafting** [comment]
Ah ok, thank you so much! I apologize for my lack of knowledge with these things. I appreciate you taking the time to answer! I do really like your mod, so thank you!
