### ISSUE TITLE
Performance is affected in 1.20.1 update.

### ISSUE THREAD

**Issue by 0Trinster0** [SammySemicolon/Malum-Mod#237]
I am happy to have the mod in 1.20.1; now there is a difficulty; I see that it affects the performance considerably; I am building a modpack and it was flowing correctly, I thought it could be the API, but by removing the Malum mod, the performance improved considerably, also the textures of the yellow leaves coming out of the trees do not load correctly and it looks black textures.

I will leave these links so you can watch the videos, one has the Malum mod and the other does not.

https://youtu.be/yoo0xqCPynk

https://youtu.be/zoffzIwd4RA

I leave also the log if needed

[latest.log](https://github.com/user-attachments/files/15891104/latest.log)

**Comment by SammySemicolon** [comment]
This has since been fixed, only an update to lodestone is needed
