### ISSUE TITLE
[1.20.1-1.6.0.1 Forge] Blocks don't display on vanilla maps nor Xaero's maps

### ISSUE THREAD

**Issue by Gronglegrowth** [SammySemicolon/Malum-Mod#239]
Vanilla maps don't display Malum's blocks - I suspect there is no map color for them specified:
![Screenshot_20240619_164124](https://github.com/SammySemicolon/Malum-Mod/assets/32804557/f2e42799-cc5f-4b2e-93d8-ae43761add0c)
As Xaero's map mods presumably rely on map colors too, they also don't display on there:
![Screenshot_20240619_164139](https://github.com/SammySemicolon/Malum-Mod/assets/32804557/d5d88739-d75c-433c-b8a1-d439b1432064)

**Comment by SammySemicolon** [comment]
Fixed in 1.6.0.2 on forge, wait for 1.6.0.3 on fabric
