### ISSUE TITLE
[1.20.1] Crash during startup

### ISSUE THREAD

**Issue by sn0wshoehare** [SammySemicolon/Malum-Mod#249]
[crash-2024-06-23_04.13.45-client.txt](https://github.com/user-attachments/files/15944285/crash-2024-06-23_04.13.45-client.txt)
[latest.log](https://github.com/user-attachments/files/15944288/latest.log)
Game crashes during startup, stops crashing when Malum is removed
Using NeoForge 47.1.106

**Comment by yrsegal** [comment]
Does this also stop if you remove Hexcasting and not Malum? Obviously that's not a workable solution, but I think that would provide some important data on what's going on

**Comment by yrsegal** [comment]
From what I can see, the mods Fusion and Hexcasting are trying to inject into the same place, but Hexcasting is doing it unsafely.

**Comment by sn0wshoehare** [comment]
Removing Hexcasting (and PAUCAL) did in fact fix the crash. I'll see about replicating it & reporting it to Hexcasting's devs.

**Comment by sn0wshoehare** [comment]
[crash-2024-06-23_15.29.14-client.txt](https://github.com/user-attachments/files/15946615/crash-2024-06-23_15.29.14-client.txt)
[latest.log](https://github.com/user-attachments/files/15946616/latest.log)
Was able to replicate the crash in an instance with minimal mods. Same thing happens - removing Malum fixes the crash, but I also found out that removing Fusion also fixes it.

**Comment by yrsegal** [comment]
... what's mixinextras doing there as an independent jar, and such an old version too?

**Comment by yrsegal** [comment]
wait, no, it's the correct version

**Comment by yrsegal** [comment]
I just misread it

**Comment by yrsegal** [comment]
But it shouldn't need to be an independent jar. I have a feeling that's related. Let me look at Fusion's code

**Comment by sn0wshoehare** [comment]
for what it's worth, i just added Rechiseled (uses Fusion) to the instance, having it enabled but not Malum doesn't crash.

**Comment by yrsegal** [comment]
Aha. I figured out why this is only happening with Malum installed - the issue doesn't *crash* unless Malum is installed but is definitely there, because Malum references the datagen class. That, we shouldn't be doing outside of datagen

**Comment by yrsegal** [comment]
Hexcasting still does something unsafe, but given that it only is relevant during datagen, it's understandable why they considered that acceptable.

**Comment by sn0wshoehare** [comment]
should this be reported to Hexcasting's repo then?

**Comment by yrsegal** [comment]
Probably not, since we shouldn't be referencing the datagen stuff outside... well, datagen, anyway.
