### ISSUE TITLE
Very Rare Crash

### ISSUE THREAD

**Issue by SharkieTV** [SammySemicolon/Malum-Mod#25]
So a person in my Better MC Plus modpack recently kept crashing from his server givng Exit Code 0 with no actual crash and all it says at the end of the log is this.

[Render thread/WARN] [net.minecraft.network.datasync.EntityDataManager/]: defineId called for: class com.sammy.malum.common.entities.boomerang.ScytheBoomerangEntity from class com.sammy.malum.common.entities.spirit.SpiritItemEntity

This doesnt crash everyone only some.

**Comment by SammySemicolon** [comment]
Closing issue since 1.16.5 became unsupported.
