### ISSUE TITLE
[1.20.1] [Tetra compat] Soul Stained Steel modules on Tetra weapons do not shatter souls

### ISSUE THREAD

**Issue by sn0wshoehare** [SammySemicolon/Malum-Mod#255]
Weapons with a module made of Soul Stained Steel do not properly shatter souls, despite having the Soul Strike property.
Mod list: 
NeoForge 47.1.106
Caelus API 3.2.0
Curios API 5.9.1
Kotlin for Forge 4.11.0
Lodestone 1.6.1
Malum 1.6.1
Tetra 6.3.0
mutil 6.1.1
![2024-07-01_02 34 25](https://github.com/SammySemicolon/Malum-Mod/assets/17393479/deb40ff7-fe5b-470d-a3f5-410fd58d8b8a)
![2024-07-01_02 34 36](https://github.com/SammySemicolon/Malum-Mod/assets/17393479/ea76a195-f083-4c63-b380-4614fca8b761)

**Comment by SammySemicolon** [comment]
Need to re-enable the tetra compat.

**Comment by SammySemicolon** [comment]
Will get to it sooner or later

**Comment by SammySemicolon** [comment]
Reintroduced the compat in 1.6.2
