### ISSUE TITLE
[1.6.2 Forge] All mote blocks missing in latest update

### ISSUE THREAD

**Issue by DelviousCrafts** [SammySemicolon/Malum-Mod#258]
Updated to the latest version of Malum to find all my mote blocks used as decoration were missing. I found that they cannot be made in the 1.6.2 version at all. Going through the mod files the block state and model files are also missing. I see that the update from 1.6.1 to 1.6.2 had something to do with the mote blocks textures, but not removal. Downgrading back to 1.6.1 did not return the mote blocks and they had to be remade.

Versions: 
- Minecraft: 1.20.1
- Forge: 47.3.5
- Curios: 5.9.1
- Lodestone: 1.6.2
- Malum: 1.6.2

**Comment by SammySemicolon** [comment]
1.6.2 updated how mote blocks work internally, instead of 8 seperate registry objects- it's just one, with the spirit type stored in memory. 
You can create mote blocks again using the lamplighter's tongs item.
