### ISSUE TITLE
[1.20.1 Fabric] Killing mobs sometimes freezes instance

### ISSUE THREAD

**Issue by DJteaCosy** [SammySemicolon/Malum-Mod#262]
Title, sometimes when I kill mobs with a crude scythe, my instance freezes and has to be closed with task manager. What happens is that at the moment of kill, the game locks up. When rebooting the instance and joining the game, it instantly crashes again, effectively bricking the save file. 

I previously used NBT explorer to delete the offending mob from the world, which fixed it before. Will do it for this occasion, but felt like I needed to submit an issue first. Crash logs attached

[crash-2024-07-19_01.02.58-server.txt](https://github.com/user-attachments/files/16322145/crash-2024-07-19_01.02.58-server.txt)
[crash-2024-07-20_21.40.51-server.txt](https://github.com/user-attachments/files/16322146/crash-2024-07-20_21.40.51-server.txt)

Modpack: All of Fabric 7
Minecraft version: 1.20.1
Fabric version: 0.15.11
Malum version: 1.20.1_1.6.1.0e-fabric

**Comment by SubordinalBlue** [comment]
That's not the current version of the AoF7 pack.
Have you tried pack version 2.4.3?
In it, Malum has been upped to `1.20.1_1.6.2.0c`.
Perhaps that version of Malum addresses that bug?

**Comment by DJteaCosy** [comment]
I haven't, didn't realise there was a new version. I'll try updating soon and see if it still happens. It's a tricky one to replicate though

**Comment by Trent2087** [comment]
> That's not the current version of the AoF7 pack. Have you tried pack version 2.4.3? In it, Malum has been upped to `1.20.1_1.6.2.0c`. Perhaps that version of Malum addresses that bug?

Still an issue with latest Malum
https://hastebin.com/share/wepowanibu.wasm

**Comment by DJteaCosy** [comment]
just checked in because I was about to close the issue since I haven't had it happen since updating the pack, but I'll hold off for Trent2087's comment

**Comment by mrsterner** [comment]
This is an issue with portinglib if anything, ill disable that part of the code until portinglib updates
