### ISSUE TITLE
Possible to create tool with negative durability

### ISSUE THREAD

**Issue by Frosticle** [SammySemicolon/Malum-Mod#266]
If you have a Soulstained Steel Sword with very low durability and upgrade it to a Tyrving, the Tyrving will have negative durability. I'm guessing this happens because the Tyrving has lower durability than the sword.

Minecraft 1.20.1
Forge 47.3.0
Malum 1.6.2
Lodestone 1.6.2

**Comment by SammySemicolon** [comment]
Fixed in 1.6.2
