### ISSUE TITLE
Strange UI bug when Spirits are on the Hotbar

### ISSUE THREAD

**Issue by cranberriez** [SammySemicolon/Malum-Mod#275]
![image](https://github.com/user-attachments/assets/4cb1101a-1e23-4cf8-ba2d-b2698022bc06)

I have many mods, including Embeddium and Oculus. The effect goes away when entering any kind of menu. The textures are still present with or without shaders.

This is Forge 1.20.1, Malum version 1.20.1-1.6.2.

**Comment by mrsterner** [comment]
disable the UI thing in ImmidiatelyFast
