### ISSUE TITLE
Revoking Void Favor

### ISSUE THREAD

**Issue by LuveelVoom** [SammySemicolon/Malum-Mod#276]
I accidentally gave myself an encyclopedia esoterica, and now have void favor despite not getting to it in progression. Is there some way to revoke void favor? I can't find any command to do it, and I don't want to have it because JEI spoils lots of stuff when I have it. If this doesn't exist, a method for doing this would be greatly appreciated :)

**Comment by mrsterner** [comment]
delete malum_extra.json
