### ISSUE TITLE
Farming For Blockheads Compat Issue

### ISSUE THREAD

**Issue by Baelarius** [SammySemicolon/Malum-Mod#28]
The Farming For Blockheads Compat appears to have the following issue:

[14:47:38] [main/ERROR]: Parsing error loading Farming for Blockheads data file at malum:farmingforblockheads_compat/saplings.json
com.google.gson.JsonSyntaxException: Expected item to be an item, was unknown string 'malum_runewood_sapling'

I believe you should just need to change the string 'malum_runewood_sapling' to 'malum:runewood_sapling'

**Comment by SammySemicolon** [comment]
Yeah, I was really tired when I wrote that haha :)
I fixed this issue already, an update will come out soon!

**Comment by Baelarius** [comment]
Awesome, it happens.

---
Bryan Lee Briggs
-------------------------------------------------
"Socialism, like the ancient ideas from which it springs, confuses the distinction between government and society. As a result of this, every time we object to a thing being done by government, the socialists conclude that we object to its being done at all." - Frederic Bastiat

________________________________
