### ISSUE TITLE
Wicked Intent effect missing image & missing JEED compat

### ISSUE THREAD

**Issue by Cicopath** [SammySemicolon/Malum-Mod#280]
Fabric 1.20.1, latest version of Malum.

I'm unsure whether these effects are actually obtainable in Survival, but I'm going through all of the effects in my modpack in Creative to make sure they all have a description and an item that relates to the respective effect. Since Malum's effect descriptions have a unique theme, I thought it'd be best to report the issue here since the mod already adds some JEED compatibility (let alone the fact that I suck at trying to match the theme 😭)

The below effects don't have descriptions:
![image](https://github.com/user-attachments/assets/c6f8066e-8469-476c-a23e-04b696326578)

In addition, Wicked Intent has a missing texture, as seen in the above screenshot.

**Comment by SammySemicolon** [comment]
Fixed in 1.6.2
