### ISSUE TITLE
[Fabric] Game won't start with Malum installed

### ISSUE THREAD

**Issue by dainekoichi** [SammySemicolon/Malum-Mod#281]
For CurseForge, I've had to manually add the prerequisties.

Here's the complete list:
![image](https://github.com/user-attachments/assets/585deb01-b2a3-4aa5-83e6-6cfb5141abf6)

Here's the crash and logs:
![image](https://github.com/user-attachments/assets/8890a2c8-fe73-4507-8bca-de4d5e8a1cf4)
[crash-2024-09-08_11.00.16-client.txt](https://github.com/user-attachments/files/16920584/crash-2024-09-08_11.00.16-client.txt)

**Comment by dainekoichi** [comment]
I've been playing with Malum before the latest update, so there might be something with the latest built for Fabric

**Comment by mrsterner** [comment]
Update lodestone
