### ISSUE TITLE
[Enhancement] Lower Runetree Spawns

### ISSUE THREAD

**Issue by SaltSouls** [SammySemicolon/Malum-Mod#296]
Right now rune trees spawn a bit to frequently, and it is very apparent in biomes where there are little to no trees that generate. I would suggest either lowering the amount they spawn by around half, and or limiting them to only be able to spawn in biome in which there are many trees, that way the other trees help hide/limit how often they spawn. I also imagine since these are used for the various rituals and the like, and are magical in nature, that they should be on the rarer side of things.

**Comment by SammySemicolon** [comment]
Fixed in 1.6.4
