### ISSUE TITLE
[Request] Add tag for spirit items

### ISSUE THREAD

**Issue by Noaaan** [SammySemicolon/Malum-Mod#297]
We are planning on adding better mod compatability for Spectrum, as a part of https://github.com/DaFuqs/Spectrum/pull/520
One thing we noticed is the lack of a tag for the spirit items. Ideally, this would be added to Malum itself, to cause less confusion.
This is what we added to `malum/tags/items/spirit_crystals.json`:
```json
{
  "values": [
    "malum:sacred_spirit",
    "malum:wicked_spirit",
    "malum:arcane_spirit",
    "malum:eldritch_spirit",
    "malum:aerial_spirit",
    "malum:aqueous_spirit",
    "malum:earthen_spirit",
    "malum:infernal_spirit"
  ]
}
```

**Comment by SammySemicolon** [comment]
Done in 1.6.4
