### ISSUE TITLE
Possible comatability issue causing servercrash 

### ISSUE THREAD

**Issue by TheNutFather** [SammySemicolon/Malum-Mod#3]
[crash-2021-05-23_19.10.01-server.txt](https://github.com/SammySemicolon/Malum-Mod/files/6533952/crash-2021-05-23_19.10.01-server.txt)

**Comment by TheRanker** [comment]
This has nothing to do with malum mod.

Entity being ticked --
Details:
	Entity Type: minecraft:fireball (net.minecraft.entity.projectile.FireballEntity)
	Entity ID: 54757
	Entity Name: Fireball
	Entity's Exact location: -459.59, 65.65, 269.88
	Entity's Block location: World: (-460,65,269), Chunk: (at 4,4,13 in -29,16; contains blocks -464,0,256 to

**Comment by SammySemicolon** [comment]
Even if, `at com.sammy.malum.MalumHelper.heldItem(MalumHelper.java:427) ~[?:1.16.5-0.2.1] {re:classloading}` is mentioned in the error log. I might as well look into it <3

**Comment by SammySemicolon** [comment]
![image](https://user-images.githubusercontent.com/69329424/119386452-d4d25500-bcc7-11eb-87af-90af7080c8d0.png)
This is the exception that causes the crash, I forgot to add null checks to my method! 
Thank you for the issue!
