### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by solonovamax** [SammySemicolon/Malum-Mod#302]
Hey,

I just noticed that the Malum mod isn't licensed under a license, however it depends on Lodestone which is licensed under the GPLv3

as-per the GPL's terms, this mod should then be licensed under the GPL or a [GPL compatible license](https://opensource.stackexchange.com/a/4557)

**Comment by SammySemicolon** [comment]
Added the LGPL 3.0 license

**Comment by solonovamax** [comment]
I think you forgor to include the normal GPL

usually when using the LGPL you need to include both the GPL license text as well as the LGPL license text (what you added) lol
