### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by pibblepower** [SammySemicolon/Malum-Mod#305]
when installing the newest version, the game crashed when interacting with a mob (a evil craft silverfish). I checked the crash report, and it seems that this mod and ars scalaes may be responsible. I can't even play the world anymore, because the game crashes immediately when logging back in. Here's the crash report: 
[crash-2024-10-26_23.37.08-server.txt](https://github.com/user-attachments/files/17532704/crash-2024-10-26_23.37.08-server.txt)

**Comment by SammySemicolon** [comment]
This is an incompatibility with one of the ars magicka addons, which I believe has been fixed in an update on their side
