### ISSUE TITLE
Crash on Ceaseless Impetus

### ISSUE THREAD

**Issue by BumbleCrashes** [SammySemicolon/Malum-Mod#32]
The Ceaceless impetus item crashes the game when the holder dies while having some potion effects (entity tick). 
So far i have tried Speed, Hunger and Wither.
Dying while having hunger (only tried with a husk attack) crashes the game.
With wither it's werid since it doesn't crash, but it doesnt trigger the totem animation and doesn't give any effects.
Speed didn't crashed so i assume maybe some potion effects crash, or maybe only negative effects.
Anyway im terrible at explaining so here's the crashlog that'll tell everything: https://pastebin.com/ZC6q1KKg
While im' at it i suggest that the Ceaseless Impetus should give the "Post mortem" achievement after using it.
:)

**Comment by SammySemicolon** [comment]
The post Mortem thing I’ll be sure to look into and add it :) being honest I didn’t even know there was an achievement like that. 
I haven’t had much time to test the release for bugs as I had to leave my home for a few days, I won’t be back till 31st

**Comment by SammySemicolon** [comment]
Fixed in 1.1.2
