### ISSUE TITLE
Lang entry for Haunted enchant is invalid

### ISSUE THREAD

**Issue by LegendaryTot** [SammySemicolon/Malum-Mod#33]
Enchant is "Haunted" so entry should be `enchantment.malum.haunted.desc`. However looks like the entry was added as `enchantment.malum.haunting.desc`.

**Comment by SammySemicolon** [comment]
Thank u for telling me I’ll fix it up :)

**Comment by SammySemicolon** [comment]
Forgot to fix in 1.1.2, fixed in indev. Expect to see it working soon-ish :)
