### ISSUE TITLE
Rendering screen crash?

### ISSUE THREAD

**Issue by BumbleCrashes** [SammySemicolon/Malum-Mod#34]
So this happened on the latest malum version where it just crashed right when i opened a chest. but trying to replicate the crash seems to be difficult as it seems to be very rare ,but i can confirm it's malum since not enough crashes tags this mod as suspect from causing the crash.
The log for more info: https://pastebin.com/77vxrUYx

**Comment by SammySemicolon** [comment]
This crash should happen while you hover over an item, are you by chance able to tell me what that item is?

**Comment by SammySemicolon** [comment]
Actually! Are you by chance using a different language?

**Comment by SammySemicolon** [comment]
Hmm no you're not

**Comment by itsdinkd** [comment]
are you ever going to push these fixes to a curseforge release? builds are great for players who run the mod on single player, but do not help modpacks, as they need a curseforge release.
