### ISSUE TITLE
Exception in server tick loop Crash

### ISSUE THREAD

**Issue by BumbleCrashes** [SammySemicolon/Malum-Mod#36]
So yeah... another crash...
This time a really weird one since it happened when i was defeating an undead army from a mod with the scythe.
The werid part is that the game ticks stopped before it crashed (Mobs stopped moving) and the log files detected that not only malum, but also minecraft and forge were also tagged as suspected. so maybe this is more related to the game itself or minecraft forge but since malum was also responsible for the game crashing, i wanted to report this issue here.
If you feel that this has nothing to do with the mod or it's an error that you can't fix, then that's ok, im not a programmer (yet) so i cant determine what's happening.
Log: https://pastebin.com/0JQnGB29

**Comment by SammySemicolon** [comment]
It's an infinite loop of the scythe hitting something, and then triggering malum's 'onhiteffects'. One of your onhiteffects seems to cause the scythe to strike again, which repeats the loop. I redid the 'onhiteffects' code quite a bunch in the upcoming update, would you mind pinging me on the discord server or private messaging me? I'll send you a build of the mod and you can test for me if the bug still happens.
