### ISSUE TITLE
cleansed rock types.

### ISSUE THREAD

**Issue by MercilessArchitect** [SammySemicolon/Malum-Mod#39]
will you be adding the cleansed rock types from 1.16 back to 1.18? also the little ether lights. as a builder, i did use both of those blocks in my work several times, and was dissapointed that thry did not get ported over to 1.18

**Comment by SammySemicolon** [comment]
at some point, maybe. I'd like them to have more distinct textures from tainted/twisted rock and want them to fit in more with the wood sets
