### ISSUE TITLE
Crash on startup - 0.2.2

### ISSUE THREAD

**Issue by MindFaer** [SammySemicolon/Malum-Mod#4]
[crash-2021-05-27_00.38.14-client.txt](https://github.com/SammySemicolon/Malum-Mod/files/6551169/crash-2021-05-27_00.38.14-client.txt)

**Comment by Elianthony** [comment]
[latest.log](https://github.com/SammySemicolon/Malum-Mod/files/6551445/latest.log)

Another more detailed log with the block id conflict

**Comment by Elianthony** [comment]
Example of error in log: [02:51:19] [modloading-worker-3/WARN]: Registry Item: Override did not have an associated owner object. Name: malum:encyclopedia_arcana Value: air

**Comment by Elianthony** [comment]
the crash log is the same of @mindfaer

**Comment by Elianthony** [comment]
The version is: malum-1.16.5-0.2.2.jar

**Comment by Elianthony** [comment]
in version  malum-1.16.5-0.2.1.jar the error did not occurred

**Comment by sirben99** [comment]
Can confirm, 0.2.2 crashes on startup.

Forge: 36.1.24
Minecraft: 1.16.5
Malum: 1.16.5-0.2.2
Curios: 1.16.5-4.0.5.1
Other mods: No
Launcher: MultiMc

Crash.txt:
https://pastebin.com/q8vmN6cT

[crash-2021-05-27_15.16.52-client.txt](https://github.com/SammySemicolon/Malum-Mod/files/6553885/crash-2021-05-27_15.16.52-client.txt)

Latest.log:
https://pastebin.com/0yjV65Vy

[latest.log](https://github.com/SammySemicolon/Malum-Mod/files/6553887/latest.log)

**Comment by SammySemicolon** [comment]
Fixed in most recent release

**Comment by Elianthony** [comment]
Thanks for support!!!
