### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by LunarFactory** [SammySemicolon/Malum-Mod#48]
[latest.log](https://github.com/SammySemicolon/Malum-Mod/files/8069618/latest.log)
strange. Killing mob with Soul stained Scythe(Rebound I, Haunted II) and killed Monsters, and long error.

**Comment by SammySemicolon** [comment]
Looks like some infinite loop

**Comment by LunarFactory** [comment]
I have some videos for that moment. If you need, I'll send you.

**Comment by SammySemicolon** [comment]
Sure, post them on discord

**Comment by LunarFactory** [comment]
I uploaded on Malum discord. If you need more information, i'll send it right back.
