### ISSUE TITLE
Spirit Jar QOL and Silk Touch

### ISSUE THREAD

**Issue by lol123123987** [SammySemicolon/Malum-Mod#5]
One thing I've noticed is that R-Clicking the Spirit Jar gives you the highest number of spirits possible.

I suggest to make it give you only one spirit, as most recipes with spirits only require one or two of them, so I think anyone would prefer to right click the jar 2-3 times to extract just as many as they need, instead of grabbing a pile of them and running back to put them in the jar again.

Also, i think it would be neat to be able to grab the jars without having the spirits spill out, if using Silk Touch. This would be quite balanced, since it's only one type of soul per jar, but it would still be useful for dedicated players that want to travel around with their spirits in a shulker box/E chest.

**Comment by SammySemicolon** [comment]
I'll make the spirit jar result in one spirit when right clicking normally, sneak right clicking will take out as many as possible.
I'll think about the jar not spilling out spirits with silk touch
Thanks for the ideas!
