### ISSUE TITLE
Scythe StackOverflowError

### ISSUE THREAD

**Issue by AnnaErisian** [SammySemicolon/Malum-Mod#55]
Appears to be unsolved in version 1.2.2, with Curios 5.0.6.0, Forge 39.0.88

Abridged log from the pack I was making when I found this crash: [HERE](https://pastebin.com/RaubFL2G)

Recreation in the minimal scenario outlined above [HERE](https://pastebin.com/Jh7bgypN)

In both cases, the stackoverflow is output repeatedly.  For the sake of page load times, I've included one instance of the repeated log sequence in each case

Recreation: Summon way too many mobs (15 presses of an oak button onto a repeating command block does the trick - or just dump chicken in until they're all taking crush damage lmao) into a 5x5 cage, swing the haunted steel scythe into the horde.  I could swear it happened with less once, but that seems to be a consistent amount.

**Comment by SammySemicolon** [comment]
I belive this has been fixed already, if you join the discord server or are already in it there's a 1.3 beta there. If you want you can check if it crashes there or not.
