### ISSUE TITLE
Crash on clicking New World when turning down chance of Runewood generation

### ISSUE THREAD

**Issue by AnnaErisian** [SammySemicolon/Malum-Mod#56]
Crash report [HERE](https://pastebin.com/2ACEPu0m)

Replication: Install Malum 1.2.2, with Curios 5.0.6.0, Forge 39.0.88.  Start the game to generate the config.  In the config, set, for example, `runewoodCommonChance = 0.009`, though any value smaller than 0.01 seems to trigger the issue.

**Comment by SammySemicolon** [comment]
I belive this has also been fixed already, and the value was 0.005 iirc. I appreciate the feedback though! :)
