### ISSUE TITLE
Crash related to rebound scythes

### ISSUE THREAD

**Issue by BumbleCrashes** [SammySemicolon/Malum-Mod#6]
Killing an entity that posess no spirits with a boomerang scythe attack causes a server crash with the scythe entity being ticked.
This only occurs with some modded mobs like ars nouveau wildens (so this does not happen with vanilla mobs), and only occurs with the boomerang attack, killing said mobs with regular scythe strikes will not crash the game.
Here's the link tho the crash log for more details : https://pastebin.com/fKQvEuPF

**Comment by SammySemicolon** [comment]
Hey, thank you for the issue report. 
I'll get to fixing it right away, do you think you could give me the id's of ars nouveau entities and what spirits you think they should have? I might aswell add compat to the mod <3

**Comment by BumbleCrashes** [comment]
sure! about the entity id's i think you mean these: 
ars_nouveau:carbuncle
ars_nouveau:whelp
ars_nouveau:wixie
ars_nouveau:wilden_hunter
ars_nouveau:wilden_stalker
ars_nouveau:wilden_guardian
ars_nouveau:ally_vex
ars_nouveau:sylph
if i have mistaken the id's i apologize since im a bit of a dummy with this :(
Now, about the mobs dropping spirits...
I tink the wilden hunters should drop aerial because their agility and arcane because they summon wolves.
wilden stalkers aerial because they fly. They dont seem magical enough to me to have arcane spirits.
wilden guardians earthen and arcane because they are strong foes and shot lasers. Maybe aquatic because they resemble a guardian but idk.
ally vexes should not be touched because they already drop spirits as they are the same entity as the vanilla ones
carbuncles arcane spirits because they are magical (duh) and maybe holy because they cute :3
whelps and sylphs arcane and aerial because they fly.
And thats all i have in mind. Hope this info results you useful :)

**Comment by SammySemicolon** [comment]
I haven't had time to test the change, but I'm pretty sure it should not crash in the most recent version. Thanks for your thoughts too
