### ISSUE TITLE
Game crash on loading save

### ISSUE THREAD

**Issue by Wilsoghn** [SammySemicolon/Malum-Mod#60]
Placed an item pedestal, and now the game crashes when I load a world with them in it.
Crash report:
[crash-2022-03-21_21.47.28-client.txt](https://github.com/SammySemicolon/Malum-Mod/files/8319335/crash-2022-03-21_21.47.28-client.txt)

**Comment by SammySemicolon** [comment]
Fixed this in dev build, will release soon
