### ISSUE TITLE
crash on world load

### ISSUE THREAD

**Issue by TheNimbleNinja** [SammySemicolon/Malum-Mod#63]
https://gist.github.com/TheNimbleNinja/3fedcf25ae449871d34425811d3398ee

**Comment by SammySemicolon** [comment]
I added a non-null check to my code. However, this seems to be an issue on someone else's side, the spawn reason should never be null. Try and look around the issue tracker's of your entity-adding mods

**Comment by TheNimbleNinja** [comment]
i have no idea wat causeed the crash it pointed to your mod thats why its here

**Comment by TheNimbleNinja** [comment]
im seeing it mention lava monster in the log
