### ISSUE TITLE
CF Update request for 1.16

### ISSUE THREAD

**Issue by SirOMGitsYOU** [SammySemicolon/Malum-Mod#64]
Hi,

I run a large modapck and official server and I am getting people concerned with the "Malum" sapling warning message that you fixed back in December for the compact with farming for blockheads. 

Is there an ETA of when you could fix this to help us remove this error message, thank you :)

**Comment by SammySemicolon** [comment]
Iirc I fixed this only for 1.18.1, I advise against using the 1.16.5 version. 
There's no ETA as 1.16.5 is stinky and unsupported by me, I simply do not have the time

**Comment by SirOMGitsYOU** [comment]
> Iirc I fixed this only for 1.18.1, I advise against using the 1.16.5 version. There's no ETA as 1.16.5 is stinky and unsupported by me, I simply do not have the time

Ah, I see okay - It does look to be fixed in the current 1.16 code, are you able to just release the 1.16 code to Curseforge just at least so we can use it as is even if it is abandoned for 1.16 until we can safely move to 1.18

**Comment by SammySemicolon** [comment]
I could compile whatever I have for 1.16 for you, but I'd rather not release that since it's not that complete. Midway through updating the mod I ported to 1.18.1 so the 1.16.5 branch is a bit behind

**Comment by SirOMGitsYOU** [comment]
> I could compile whatever I have for 1.16 for you, but I'd rather not release that since it's not that complete. Midway through updating the mod I ported to 1.18.1 so the 1.16.5 branch is a bit behind

I see okay - if you were to compile it, it's not something Curseforge would let us use without it being on their platform per their t&cs for modpacks on the platform. 

You could allow them to use third party builds of Malum via their submission form - 

https://docs.google.com/forms/d/e/1FAIpQLSdHHXGV7bfMt_Cjb_pODHf30hkcQHCbMWo1t_NOaOkqve6HkQ/viewform

**Comment by SammySemicolon** [comment]
Yeah well, I don't want people using the 1.16.5 version to begin with so, yeah.
