### ISSUE TITLE
Crash on Altar Crafting

### ISSUE THREAD

**Issue by Brisngir** [SammySemicolon/Malum-Mod#68]
Though the initial crafting of dust was without issue, it seems that crafting anything that requires pulling from additional pedestals causes a crash just before the altar creates the item. Tested on Runewood Totem Base and Soul Stained Steel recipes, and enclosed is the crash report for the latter.

I use six pedestals, three in a row on opposite sides of the altar, with one block of space between them and the altar. 

[crash-2022-04-22_19.47.05-server.txt](https://github.com/SammySemicolon/Malum-Mod/files/8545787/crash-2022-04-22_19.47.05-server.txt)

**Comment by SammySemicolon** [comment]
This should be fixed on 1.3.4
