### ISSUE TITLE
Lavender missing tag

### ISSUE THREAD

**Issue by WenXin20** [SammySemicolon/Malum-Mod#7]
`Minecraft v1.16.5`
`Forge v36.1.24`
`Malum v0.2.2.4`

Lavender is currently missing the `#minecraft:tall_flowers` block and item tag, which would allow bees to pollinate it and for it to be used in recipes respectively.

**Comment by SammySemicolon** [comment]
Fixed, thank you <3

**Comment by WenXin20** [comment]
Awesome, np!
