### ISSUE TITLE
1.18.2 Just enough Effect Descriptions support

### ISSUE THREAD

**Issue by zachsai** [SammySemicolon/Malum-Mod#70]
![image](https://user-images.githubusercontent.com/63996164/165212350-c1c43a85-ebe5-4f23-a357-7fb026ef43c1.png)
Could you add JEED Support

**Comment by SammySemicolon** [comment]
Sure yeah, I'll look into it :)

**Comment by SammySemicolon** [comment]
My tired ass just looked up 'JEED' on google and deadass expected to find the mod lol

**Comment by SammySemicolon** [comment]
Added :)
