### ISSUE TITLE
[Feature Request]1.18.2 Config addition

### ISSUE THREAD

**Issue by Tyrius1** [SammySemicolon/Malum-Mod#72]
Could you add Biome Whitelist entries for the Runewood Trees and the Soulstone ore?

I would like to isolate these 2 amazing features to specific biomes in order to create greater excitement around their discovery within my specific modpack that I am developing.

**Comment by SammySemicolon** [comment]
Yes! I'll be adding this soon in form of biome tags.
1.18.2 introduced tags for every single registry type. Biomes, features, items, blocks, mobs, etc. Rather than just items & blocks.
There will be a tag that you can edit with json, which determines what biomes can support a given feature.

**Comment by Tyrius1** [comment]
Woot exciting! Will this be in the form of a datapack then?

**Comment by SammySemicolon** [comment]
Yeah- biome tags work like any other tag I believe, you may simply add a file to your tags location titled 'runewood_tree_biome' and add some biome ids in there and bam, runewood trees spawn there.
