### ISSUE TITLE
[Suggestion] Add sided inputs?

### ISSUE THREAD

**Issue by 1mphuls3** [SammySemicolon/Malum-Mod#73]
It would be nice to have some sort of sided input for hopper insertion of items. I think that adding something like this:

**public <T> LazyOptional<T> getCapability(@Nonnull Capability<T> cap, Direction direction) {
        if (cap == CapabilityItemHandler.ITEM_HANDLER_CAPABILITY && !(direction == Direction.UP && direction == Direction.DOWN)) {
            return spiritInventory.invOptional.cast();
        } else if (cap == CapabilityItemHandler.ITEM_HANDLER_CAPABILITY) {
            return inventory.invOptional.cast();
        }
        return super.getCapability(cap, direction);
    }**

to the SpiritAltarTileEntity class might work, so spirits would be able to be hopper inputted from any direction except top and bottom.
Having auto outputs are already possible, just filtering a hopper on the bottom to whatever output you need.
I thought that this would be a nice feature since vanilla furnaces already have sided input and output.

**Comment by SammySemicolon** [comment]
Yeah, I need to get around to adding some means of accessing the spirit inventory of various blocks to pipes and hoppers.
The best way to go about this is to just automatically filter spirits into the spirit inventory, and items into the item inventory when fed into a pipe, but with how the inventory system I use works (separate instances for separate item storage), it's a little difficult. I'll be looking into a solution soon enough
