### ISSUE TITLE
[Bug]: Malum armors don't render in-game

### ISSUE THREAD

**Issue by Raidobw2** [SammySemicolon/Malum-Mod#74]
The armors don't seem to render in-game, here are the versions I'm using:
MC: `1.18.2`
Forge: `40.1.19`
Malum: `malum-1.18.2-1.3.5.jar`
OrtusLib: `ortus-1.18.2-1.0.jar`

Here's a demonstration:

https://user-images.githubusercontent.com/17010632/167772767-9e26dab7-a6ff-4b97-9514-11163d39077e.mp4

Thanks in advance and let me know if you need anything else, or testing!

**Comment by SammySemicolon** [comment]
Yeah they don't, I fixed this already and it'll work in 1.4.
I felt I don't need to actually upload this as a hotfix since 1.3.4 & 1.3.5 are the exact same apart from the ortuslib requirement.

**Comment by Raidobw2** [comment]
Alrighty, thanks for the info!

**Comment by Raidobw2** [comment]
Thank you for the hotfix!🙂
