### ISSUE TITLE
[Crash] 1.8.2: Area Damage on 60+ mobs at same time

### ISSUE THREAD

**Issue by MaoDoBan** [SammySemicolon/Malum-Mod#76]
I'm using a soul_stained_steel_scythe on 60 cows, on a creative singleplayer flat map.
The same crash occurs in my survival server too.

![2022-05-17_18 30 14](https://user-images.githubusercontent.com/11332249/168913353-0a1e2ae8-df5c-4708-bb40-815601330366.png)

[crash-2022-05-17_18.24.20-server.txt](https://github.com/SammySemicolon/Malum-Mod/files/8711655/crash-2022-05-17_18.24.20-server.txt)

**Comment by SammySemicolon** [comment]
![image](https://user-images.githubusercontent.com/69329424/169275647-30828052-64a7-47b9-bf99-ba2b7e41e547.png)
??????

**Comment by SammySemicolon** [comment]
Fixed in 1.4, will come out soon-ish?
