### ISSUE TITLE
[Bug]: belt armor don't reduce

### ISSUE THREAD

**Issue by MaoDoBan** [SammySemicolon/Malum-Mod#77]
When I equip a belt, and remove the belt, the armor don't reduce as expected.
Quit the server and rejoin (or quit singleplayer and reopen the map) reset the armor to the expected value.

MC: 1.18.2
Forge: 40.1.16
Malum: 1.3.6
OrtusLib: 1.0
Curios API (Forge): 5.0.7.0

Here's a demonstration:
https://user-images.githubusercontent.com/11332249/169175080-e701ab70-a9bb-4076-a80d-8462fafdd04b.mp4

**Comment by MaoDoBan** [comment]
Magebane belt:
![magebane belt](https://user-images.githubusercontent.com/11332249/169597006-f0a0861c-56a7-46fd-b279-d9e8abedd663.png)

**Comment by SammySemicolon** [comment]
Haha that's hillarious :)
