### ISSUE TITLE
spirit fabric ritual not activating 

### ISSUE THREAD

**Issue by skytheraiders** [SammySemicolon/Malum-Mod#78]
I made the hex ash with no problem but when I go to craft the spirit fabric, the alter doesn't do anything. Is there something I'm doing wrong?
![2022-05-20_00 04 16](https://user-images.githubusercontent.com/18493470/169448237-0c1c8dbf-28ac-4161-8efe-a063fc5de715.png)
![2022-05-20_00 04 53](https://user-images.githubusercontent.com/18493470/169448238-eb063986-1c1d-4c97-8081-efc660ca2408.png)

**Comment by skytheraiders** [comment]
The second image is of the items that the recipe needs on my top inventory row.

**Comment by SammySemicolon** [comment]
Spirits go into the altar, not on pedestals
