### ISSUE TITLE
Torch Particle Crash

### ISSUE THREAD

**Issue by WenXin20** [SammySemicolon/Malum-Mod#8]
`Minecraft v1.16.5`
`Forge v36.1.32`
`Malum v0.3.0`

I got a crash with Malum torches when placing it. On a server, I crashed client-side. Looks to be particle related. I also have the mod Sodium Reforged installed.
[Crash Report](https://gist.github.com/WenXin20/eeaf0253b4739651af008521d463b364)

**Comment by SammySemicolon** [comment]
I forgot to reply to this apprently
Sodium Reforged doesn't like Eidolon's particle rendering, which Malum uses. You can turn off "Use Vertex Array Objects" and "Use Compact Vertex Format" to fix this as far as I know.

**Comment by WenXin20** [comment]
Thanks, I'll give that a try
