### ISSUE TITLE
[Incompatibility] Scythes are incompatible with Epic Fight Mod

### ISSUE THREAD

**Issue by qVoidreaver** [SammySemicolon/Malum-Mod#81]
I'm putting together an interesting modpack to play with my friends and I came across a mismatch between the Scythes and the EpicFight Mod. As shown in the images, the Scythes are not being recognized as weapons, which makes EpicFight recognize it as if we were empty-handed, throwing punches in the air. The other weapons are being recognized normally, as shown in the images.

![2022-05-25_11 20 16](https://user-images.githubusercontent.com/106211252/170286458-cfea7b4d-2bed-4716-a734-718bd83c5e1a.png)
 
![2022-05-25_11 20 21](https://user-images.githubusercontent.com/106211252/170286553-9d99ac4b-a87d-454c-ac93-a35aef70781d.png)

![2022-05-25_11 20 36](https://user-images.githubusercontent.com/106211252/170286720-6a32a60c-32a0-432f-9764-5359f5c0c2ef.png)

![2022-05-25_11 20 41](https://user-images.githubusercontent.com/106211252/170286748-b3fd47c4-aa7d-43d1-82d1-c92e8a551625.png)

**Comment by DragonAstemirN** [comment]
hello best regards
I have seen your request and although I am not the author of the mod, I have been checking the compatibility
solution in the configuration of EpicFight Mod.


The following setting fixes the issue by adding it Epic Fight Mod.

	[custom_weaponry.malum_crude_scythe]
		armor_ignorance = 0.0
		hit_at_once = 1
		impact = 0.5
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "GREATSWORD"
		registry_name = "malum:crude_scythe"


![2022-05-28_23 47 35](https://user-images.githubusercontent.com/94336869/170854271-d7ec5ce6-cf10-4e54-bb09-d7f3b6e165ac.png)

**Comment by qVoidreaver** [comment]
> hello best regards I have seen your request and although I am not the author of the mod, I have been checking the compatibility solution in the configuration of EpicFight Mod.
> 
> The following setting fixes the issue by adding it Epic Fight Mod.

 Oh man thanks, but sorry for the trouble again, because I was testing this in many ways, but I don't know in which epic file I have to put this "code" or if I have to create a new file and put it. I watched a lot of videos and nothing helped me, if you can give me a quick but a little detailed tutorial it would really help me. I use Minecraft 1.18.2.

**Comment by DragonAstemirN** [comment]
Yes, no problem.
You have to go to the configuration folder and open the following file
![1](https://user-images.githubusercontent.com/94336869/170894094-bca04a64-1ef4-4c45-a322-ad1782164ef1.PNG)



Then look for the section [custom weaponry]
![2](https://user-images.githubusercontent.com/94336869/170893887-07702b29-ea30-4cbc-880f-f455337b5802.PNG)


and finally add the configuration.
![3](https://user-images.githubusercontent.com/94336869/170893917-3704aa25-1a69-49cd-9475-d2e0ea777e08.PNG)

I use 1.16.5 but it should be the same for 1.18
I hope it helps you

**Comment by qVoidreaver** [comment]
> Yes, no problem. You have to go to the configuration folder and open the following file ![1](https://user-images.githubusercontent.com/94336869/170894094-bca04a64-1ef4-4c45-a322-ad1782164ef1.PNG)
> 
> Then look for the section [custom weaponry] ![2](https://user-images.githubusercontent.com/94336869/170893887-07702b29-ea30-4cbc-880f-f455337b5802.PNG)
> 
> and finally add the configuration. ![3](https://user-images.githubusercontent.com/94336869/170893917-3704aa25-1a69-49cd-9475-d2e0ea777e08.PNG)
> 
> I use 1.16.5 but it should be the same for 1.18 I hope it helps you

 Thanks man, you save me
