### ISSUE TITLE
Spirit Collection Glitch

### ISSUE THREAD

**Issue by Azuriuz** [SammySemicolon/Malum-Mod#84]
![2022-05-31_22 50 25](https://user-images.githubusercontent.com/50718369/171318318-11164be4-8e5a-4ca0-ac07-4277ad5cc640.png)
These beauties often don't despawn when collected, and show but aren't collectable for other players. 
Also if a player logs off without collecting them, they are no longer collectable and just appear there, for everyone.
This is in the SpellCraft 2 Beta Modpack (not yet on curseforge) in Forge 1.16.5. 
Please lmk what other info you need.

**Comment by SammySemicolon** [comment]
Sadly 1.16.5 is unsupported by me, and honestly I don't encourage using 1.16.5 malum. 
Most you can do is /kill them
