### ISSUE TITLE
Duplication Glitch with Ars Nouveau

### ISSUE THREAD

**Issue by Cicopath** [SammySemicolon/Malum-Mod#85]
Minecraft ~1.18.1~ 1.18.2; my bad
Malum 1.3.6
Ars Nouveau 2.4.2

With Ars Nouveau, you can create your own custom spells. However, the spell, "Touch/Projectile → Break," duplicates the Runewood Obelisk when broken. I assume it duplicates the Brilliant Obelisk as well, considering it has a similar block model as the Runewood Obelisk.

**Comment by SammySemicolon** [comment]
Yeah this is an issue with how I handle multiblock item drops, it's on my side

**Comment by SammySemicolon** [comment]
Should be fixed I believe
