### ISSUE TITLE
Ether Particles Disappearing

### ISSUE THREAD

**Issue by Cicopath** [SammySemicolon/Malum-Mod#87]
Minercaft 1.18.2
Malum 1.3.6
Forge 40.1.31

When I leave a chunk with an Ether block(s) in it and let it unload, then reload the chunk, the particles of such Ether blocks disappear. This also happens when I exit and reload the world, despite being in the same chunk. However, this does _not_ occur with dyed Ether blocks.
![2022-06-03_14 59 53](https://user-images.githubusercontent.com/61031176/171933838-c5139860-f40e-4678-9b65-7c6589312198.png)
I am playing with many mods, so I'm unsure if a mod(s) is be conflicting with Malum. Though, it's quite odd that this doesn't occur with dyed Ether blocks, so I doubt a mod could be causing it. Just in case, though, here is my list of mods:
![aaa](https://user-images.githubusercontent.com/61031176/171933953-7f639ff3-0252-44ad-bc1e-365be01f8482.png)
_Mods that are also included but not present in the list of mods include: Spice of Life: Carrot Edition 1.12.0; Apple Skin 2.4.0; Twilight Forest 4.1.1052_

And finally, here is my latest.log:
[latest.log](https://github.com/SammySemicolon/Malum-Mod/files/8835152/latest.log)

**EDIT:** The one non-dyed Iridescent Ether did not have particles; it was also affected. I just replaced the block before taking the screenshot.

**Comment by SammySemicolon** [comment]
This was an issue in the base version of malum, I fixed it with a rlly temporary solution.
I'll keep this issue open in case anyone wants to help with the following 
![image](https://user-images.githubusercontent.com/69329424/173694811-2bf8d5a7-a01e-4f93-8d81-c8d6694f3736.png)

**Comment by yrsegal** [comment]
i think that optimization is silly and hurts more than it helps

**Comment by SammySemicolon** [comment]
Fixed in 1.4
