### ISSUE TITLE
Items Can Be Repaired with Incorrect Materials

### ISSUE THREAD

**Issue by Cicopath** [SammySemicolon/Malum-Mod#89]
Minercaft 1.18.2
Malum 1.3.6

As the mod is being update with more mod compatibility, there are also more problems with spirit repairing. Armor and tools from other mods can be repaired with materials they have not been crafted with or they are not meant to be repaired with. For example, anything with, "steel_," in their item ID can be repaired with steel. This is especially prevalent with Botania tools and armor, such as Manasteel tools and armor, Terrasteel armor (tools are named, "terra_," not, "terrasteel_," so they are unaffected), and Alfsteel tools and armor.

I don't know if there are more compatibility issues with item ID's regarding this scenario; but if I find any, I will try to report them.

**Comment by RealRTTV** [comment]
sammy, you should replace the itemLookup with a regex match and maybe add a modIdLookup regex too to solve this

**Comment by RealRTTV** [comment]
For example you could replace `soul_stained_steel.json` with:
```json
{
  "type": "malum:spirit_repair",
  "itemIdLookup": "soul_stained_steel_.+",
  "modIdLookup": "malum"
  "durabilityPercentage": 0.75,
  "inputs": []
...
```
inputs would be empty since everything falls under the lookups
