### ISSUE TITLE
Server Crash after doing Hallowed Gold Ritual (Also can't join world anymore)

### ISSUE THREAD

**Issue by Asveste** [SammySemicolon/Malum-Mod#9]
(Not sure if this is the right place to post, but here I go!)

I wanted to craft some Hallowed Gold, started the ritual and exactly when it finished the server crashed. I restarted the server but immediately after joining it shut down again.
I remember putting 8 Arcane Spirits on the left side and a stack of Gold Ingots in the middle. Thinking that maybe putting a stack there caused the crash, I tried to reproduce it in singleplayer but it all went well and I got my Hallowed Gold Ingots.

I looked a bit into the crash log, but everything there was beyond my knowledge, the only thing I know (from the first few lines lol), is that it may have something to do with Malum, I just don't know what.

Forge Version is 36.1.32. Yes the crashlog says OptiFine was installed on the server, but deleting it did not make my world accessible again.

Crashlog is attached.
I hope this can get fixed :')

[crash-2021-07-27_21.58.15-server.txt](https://github.com/SammySemicolon/Malum-Mod/files/6889751/crash-2021-07-27_21.58.15-server.txt)

**Comment by SammySemicolon** [comment]
Yeah the rune table sucks. Things will be a lot better once I fix things up in the next update <3

**Comment by Asveste** [comment]
Alright, I'll be waiting then :)

Luckily I got a kinda recent backup of my world so thats great ^^

**Comment by Merithor** [comment]
Come to see I'm not the only one on this... oof.
So whats said until the new update is if making Soulsteel/Hallowed Gold with the Rune Table is 1 thing at a time (1 gold 2 sacred), cant do any more then that, right?
:x

**Comment by SammySemicolon** [comment]
Awh, never thought I'd hear my mod being compared to astral. 
Sadly I'm not gonna make a fix for the runetable since it's longggg gonee (it'll return with a new purpose soon after the next big update but still)
