### ISSUE TITLE
Ceaseless Impetus bug

### ISSUE THREAD

**Issue by Kazsra** [SammySemicolon/Malum-Mod#92]
Mods: 
Controlling-forge-1.18.2-9.0+19.jar
curios-forge-1.18.2-5.0.7.0.jar
jei-1.18.2-9.5.5.174.jar
malum-1.18.2-1.3.6.jar
MouseTweaks-forge-mc1.18-2.21.jar
ortus-1.18.2-1.0.jar

The ceaseless impetus is taking durability when I die, but it doesn't revive me. Also, when I respawn none of my items drop, so they just disappear.
![you died](https://user-images.githubusercontent.com/106931437/172070688-215a27bd-00e5-42a2-b00e-853e1ea0c67a.png)
.

**Comment by swuff-star** [comment]
sammy; says this is, "totally fixed up in 1.4, epic style, with the sauce" (my words not theirs, despite the quotes), so it sounds like it's just a matter of waiting for the next release.

**Comment by Kazsra** [comment]
epic and cool
