### ISSUE TITLE
[1.18.2] Crash when attacking Minecolonies mobs with scythe 

### ISSUE THREAD

**Issue by Banh-Bao** [SammySemicolon/Malum-Mod#94]
i've crashed a server i play on twice trying to fight off minecolonies enemies with the scythe

**Comment by SammySemicolon** [comment]
Can I get a crash log?

**Comment by Banh-Bao** [comment]
https://gist.github.com/belathus/e273602198679591f81fe5934d0102ae
this was from the last time i crashed the server killing a horde of barbarians

**Comment by SammySemicolon** [comment]
This should be fixed in 1.4
