### ISSUE TITLE
KubeJS causes Crystal and Ash creation via Alchemical Impetus as well as Metallic Node Creation to not function

### ISSUE THREAD

**Issue by puncrafter** [SammySemicolon/Malum-Mod#95]
Forge Version: 40.1.48
Malum Version: 1.18.2-1.3.6
KubeJS Version: 1802.5.4-build.496

When Malum is installed alongside KubeJS, the following entries in the Encyclopedia Arcana are blank:
- Working With Ashes
- Crystal Creation

In addition, none of the recipes for creating dusts, crystals, or metallurgic nodes show up in JEI or work properly. 

![image](https://user-images.githubusercontent.com/53954921/174674466-999dcda7-4b0e-4cd4-b0e4-a6b38f703d94.png)

**Comment by MaxNeedsSnacks** [comment]
Sometimes, I really dislike how Lat just adds unrelated mods' recipes to the builtin plugin...

https://github.com/KubeJS-Mods/KubeJS/blob/1.18/main/common/src/main/java/dev/latvian/mods/kubejs/recipe/mod/MalumSpiritFocusingRecipeJS.java

~~I'll look at this in more detail tomorrow, it's 1AM for me, but something seems to be off in our parsing~~

*sigh* It was a typo...

**Comment by SammySemicolon** [comment]
:)
